import { finish, identity, naAmount, pair, type Draft } from "./builders";
import type {
  AmountStatus,
  Cadence,
  ContractTerm,
  PayrollServiceClass,
  PricingCategory,
  PricingResearchRow,
  PricingUnit,
} from "./types";

function quoteShared(params: {
  category: PricingCategory;
  slug: string;
  productName: string;
  primarySourceUrl: string;
  evidenceIds: string[];
  payrollServiceClass?: PayrollServiceClass;
  contractTerm?: ContractTerm;
}): Omit<Draft, "scenarioId"> {
  return {
    ...identity(params),
    ...naAmount,
    advertisedPlanName: null,
    advertisedAmount: null,
    advertisedCadence: null,
    advertisedUnit: "QUOTE",
    advertisedStatus: "QUOTE_REQUIRED",
    usablePlanName: null,
    usableBaseAmount: null,
    usableCadence: null,
    usableUnit: "QUOTE",
    usableStatus: "QUOTE_REQUIRED",
    monthToMonthAmount: null,
    monthToMonthAmountStatus: "NOT_APPLICABLE",
    includedSeats: null,
    contractTerm: params.contractTerm ?? "QUOTE",
    payrollServiceClass: params.payrollServiceClass ?? "NOT_APPLICABLE",
  };
}

function undisclosedShared(params: {
  category: PricingCategory;
  slug: string;
  productName: string;
  primarySourceUrl: string;
  evidenceIds: string[];
  payrollServiceClass?: PayrollServiceClass;
}): Omit<Draft, "scenarioId"> {
  return {
    ...identity(params),
    ...naAmount,
    advertisedPlanName: null,
    advertisedAmount: null,
    advertisedCadence: null,
    advertisedUnit: "NOT_APPLICABLE",
    advertisedStatus: "NOT_DISCLOSED",
    usablePlanName: null,
    usableBaseAmount: null,
    usableCadence: null,
    usableUnit: "NOT_APPLICABLE",
    usableStatus: "NOT_DISCLOSED",
    monthToMonthAmount: null,
    monthToMonthAmountStatus: "NOT_APPLICABLE",
    includedSeats: null,
    contractTerm: "NOT_DISCLOSED",
    payrollServiceClass: params.payrollServiceClass ?? "NOT_APPLICABLE",
  };
}

function crmSeat(params: {
  slug: string;
  productName: string;
  primarySourceUrl: string;
  evidenceIds: string[];
  advertisedPlanName: string;
  advertisedAmount: number;
  advertisedCadence: Cadence;
  advertisedUnit: PricingUnit;
  advertisedStatus?: AmountStatus;
  usablePlanName: string;
  usableBaseAmount: number;
  usableCadence: Cadence;
  monthToMonthAmount: number | null;
  monthToMonthAmountStatus?: AmountStatus;
  contractTerm?: ContractTerm;
}): PricingResearchRow[] {
  return pair(
    {
      ...identity({
        category: "crm",
        slug: params.slug,
        productName: params.productName,
        primarySourceUrl: params.primarySourceUrl,
        evidenceIds: params.evidenceIds,
      }),
      ...naAmount,
      advertisedPlanName: params.advertisedPlanName,
      advertisedAmount: params.advertisedAmount,
      advertisedCadence: params.advertisedCadence,
      advertisedUnit: params.advertisedUnit,
      advertisedStatus: params.advertisedStatus ?? "PUBLIC",
      usablePlanName: params.usablePlanName,
      usableBaseAmount: params.usableBaseAmount,
      usableCadence: params.usableCadence,
      usableUnit: "USER",
      usableStatus: "PUBLIC",
      monthToMonthAmount: params.monthToMonthAmount,
      monthToMonthAmountStatus: params.monthToMonthAmountStatus ?? "PUBLIC",
      includedSeats: null,
      contractTerm: params.contractTerm ?? "NOT_DISCLOSED",
      payrollServiceClass: "NOT_APPLICABLE",
    },
    ["crm-5", "crm-10"],
  );
}

function payrollBasePlus(params: {
  slug: string;
  productName: string;
  primarySourceUrl: string;
  evidenceIds: string[];
  advertisedPlanName: string;
  advertisedAmount: number;
  usablePlanName: string;
  usableBaseAmount: number;
  extraSeatAmount: number;
  payrollServiceClass: PayrollServiceClass;
  requiredAddonFor5?: number;
  requiredAddonFor10?: number;
  contractTerm?: ContractTerm;
}): PricingResearchRow[] {
  const shared = {
    ...identity({
      category: "payroll" as const,
      slug: params.slug,
      productName: params.productName,
      primarySourceUrl: params.primarySourceUrl,
      evidenceIds: params.evidenceIds,
    }),
    extraSeatAmount: params.extraSeatAmount,
    extraSeatAmountStatus: "PUBLIC" as AmountStatus,
    onboardingAmount: null as number | null,
    onboardingAmountStatus: "NOT_APPLICABLE" as AmountStatus,
    minimumSeats: null as number | null,
    advertisedPlanName: params.advertisedPlanName,
    advertisedAmount: params.advertisedAmount,
    advertisedCadence: "MONTHLY" as Cadence,
    advertisedUnit: "BASE_PLUS_UNIT" as PricingUnit,
    advertisedStatus: "PUBLIC" as AmountStatus,
    usablePlanName: params.usablePlanName,
    usableBaseAmount: params.usableBaseAmount,
    usableCadence: "MONTHLY" as Cadence,
    usableUnit: "BASE_PLUS_UNIT" as PricingUnit,
    usableStatus: "PUBLIC" as AmountStatus,
    monthToMonthAmount: params.usableBaseAmount,
    monthToMonthAmountStatus: "PUBLIC" as AmountStatus,
    includedSeats: null as number | null,
    contractTerm: params.contractTerm ?? ("MONTHLY" as ContractTerm),
    payrollServiceClass: params.payrollServiceClass,
  };
  const addon5 = params.requiredAddonFor5;
  const addon10 = params.requiredAddonFor10;
  return [
    finish({
      ...shared,
      scenarioId: "payroll-5",
      requiredAddonAmount: addon5 ?? null,
      requiredAddonAmountStatus: addon5 == null ? "NOT_APPLICABLE" : "PUBLIC",
    }),
    finish({
      ...shared,
      scenarioId: "payroll-10",
      requiredAddonAmount: addon10 ?? null,
      requiredAddonAmountStatus: addon10 == null ? "NOT_APPLICABLE" : "PUBLIC",
    }),
  ];
}

const zohoCrmShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "crm",
    slug: "zoho-crm",
    productName: "Zoho CRM",
    primarySourceUrl: "https://www.zoho.com/en-us/crm/zohocrm-pricing.html",
    evidenceIds: ["zoho-crm-pricing"],
  }),
  ...naAmount,
  advertisedPlanName: "Free",
  advertisedAmount: 0,
  advertisedCadence: "FREE",
  advertisedUnit: "FREE",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Standard",
  usableBaseAmount: 14,
  usableCadence: "ANNUAL_BILLED_MONTHLY",
  usableUnit: "USER",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 20,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "NOT_APPLICABLE",
};

const housecallAdvertised = {
  advertisedPlanName: "Basic",
  advertisedAmount: 59,
  advertisedCadence: "ANNUAL_BILLED_MONTHLY" as Cadence,
  advertisedUnit: "INCLUDED_CAP" as PricingUnit,
  advertisedStatus: "PUBLIC" as AmountStatus,
  contractTerm: "MONTHLY" as ContractTerm,
  payrollServiceClass: "NOT_APPLICABLE" as PayrollServiceClass,
};

const housecall1to4: Draft = {
  ...identity({
    category: "field-service",
    slug: "housecall-pro",
    productName: "Housecall Pro",
    primarySourceUrl: "https://www.housecallpro.com/pricing/",
    evidenceIds: ["housecall-pro-pricing"],
  }),
  ...naAmount,
  ...housecallAdvertised,
  scenarioId: "fsm-1-4",
  usablePlanName: "Essentials",
  usableBaseAmount: 149,
  usableCadence: "ANNUAL_BILLED_MONTHLY",
  usableUnit: "INCLUDED_CAP",
  usableStatus: "PUBLIC",
  includedSeats: 5,
  extraSeatAmount: null,
  extraSeatAmountStatus: "NOT_APPLICABLE",
  monthToMonthAmount: 189,
  monthToMonthAmountStatus: "PUBLIC",
};

const housecall2to8: Draft = {
  ...identity({
    category: "field-service",
    slug: "housecall-pro",
    productName: "Housecall Pro",
    primarySourceUrl: "https://www.housecallpro.com/pricing/",
    evidenceIds: ["housecall-pro-pricing"],
  }),
  ...naAmount,
  ...housecallAdvertised,
  scenarioId: "fsm-2-8",
  usablePlanName: "Max",
  usableBaseAmount: 299,
  usableCadence: "ANNUAL_BILLED_MONTHLY",
  usableUnit: "INCLUDED_CAP",
  usableStatus: "PUBLIC",
  includedSeats: 8,
  extraSeatAmount: 35,
  extraSeatAmountStatus: "PUBLIC",
  monthToMonthAmount: 329,
  monthToMonthAmountStatus: "PUBLIC",
};

const kickserv1to4: Draft = {
  ...identity({
    category: "field-service",
    slug: "kickserv",
    productName: "Kickserv",
    primarySourceUrl: "https://kickserv.com/pricing",
    evidenceIds: ["kickserv-pricing", "kickserv-home"],
  }),
  ...naAmount,
  scenarioId: "fsm-1-4",
  advertisedPlanName: "Start",
  advertisedAmount: 60,
  advertisedCadence: "MONTHLY",
  advertisedUnit: "INCLUDED_CAP",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Start",
  usableBaseAmount: 60,
  usableCadence: "MONTHLY",
  usableUnit: "INCLUDED_CAP",
  usableStatus: "PUBLIC",
  includedSeats: 5,
  monthToMonthAmount: 60,
  monthToMonthAmountStatus: "PUBLIC",
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "NOT_APPLICABLE",
};

const kickserv2to8: Draft = {
  ...identity({
    category: "field-service",
    slug: "kickserv",
    productName: "Kickserv",
    primarySourceUrl: "https://kickserv.com/pricing",
    evidenceIds: ["kickserv-pricing", "kickserv-home"],
  }),
  ...naAmount,
  scenarioId: "fsm-2-8",
  advertisedPlanName: "Start",
  advertisedAmount: 60,
  advertisedCadence: "MONTHLY",
  advertisedUnit: "INCLUDED_CAP",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Run",
  usableBaseAmount: 119,
  usableCadence: "MONTHLY",
  usableUnit: "INCLUDED_CAP",
  usableStatus: "PUBLIC",
  includedSeats: 10,
  monthToMonthAmount: 119,
  monthToMonthAmountStatus: "PUBLIC",
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "NOT_APPLICABLE",
};

const mhelpdesk1to4: Draft = {
  ...identity({
    category: "field-service",
    slug: "mhelpdesk",
    productName: "mHelpDesk",
    primarySourceUrl: "https://forum.mhelpdesk.com/en/articles/12641238-plans-and-pricing",
    evidenceIds: ["mhelpdesk-help-pricing"],
  }),
  ...naAmount,
  scenarioId: "fsm-1-4",
  advertisedPlanName: "Pro",
  advertisedAmount: 169,
  advertisedCadence: "MONTHLY",
  advertisedUnit: "INCLUDED_CAP",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Growth",
  usableBaseAmount: 249,
  usableCadence: "MONTHLY",
  usableUnit: "INCLUDED_CAP",
  usableStatus: "PUBLIC",
  includedSeats: 8,
  extraSeatAmount: null,
  extraSeatAmountStatus: "NOT_DISCLOSED",
  monthToMonthAmount: 249,
  monthToMonthAmountStatus: "PUBLIC",
  contractTerm: "MONTHLY",
  payrollServiceClass: "NOT_APPLICABLE",
};

const mhelpdesk2to8: Draft = {
  ...identity({
    category: "field-service",
    slug: "mhelpdesk",
    productName: "mHelpDesk",
    primarySourceUrl: "https://forum.mhelpdesk.com/en/articles/12641238-plans-and-pricing",
    evidenceIds: ["mhelpdesk-help-pricing"],
  }),
  ...naAmount,
  scenarioId: "fsm-2-8",
  advertisedPlanName: "Pro",
  advertisedAmount: 169,
  advertisedCadence: "MONTHLY",
  advertisedUnit: "INCLUDED_CAP",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Success",
  usableBaseAmount: 374,
  usableCadence: "MONTHLY",
  usableUnit: "INCLUDED_CAP",
  usableStatus: "PUBLIC",
  includedSeats: 10,
  extraSeatAmount: null,
  extraSeatAmountStatus: "NOT_DISCLOSED",
  monthToMonthAmount: 374,
  monthToMonthAmountStatus: "PUBLIC",
  contractTerm: "MONTHLY",
  payrollServiceClass: "NOT_APPLICABLE",
};

const connecteamShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "field-service",
    slug: "connecteam",
    productName: "Connecteam",
    primarySourceUrl: "https://connecteam.com/pricing",
    evidenceIds: ["connecteam-pricing"],
  }),
  ...naAmount,
  advertisedPlanName: "Small Business Plan",
  advertisedAmount: 0,
  advertisedCadence: "FREE",
  advertisedUnit: "FREE",
  advertisedStatus: "PUBLIC",
  usablePlanName: null,
  usableBaseAmount: null,
  usableCadence: null,
  usableUnit: "NOT_APPLICABLE",
  usableStatus: "NOT_APPLICABLE",
  monthToMonthAmount: 0,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: 10,
  contractTerm: "MONTHLY",
  payrollServiceClass: "NOT_APPLICABLE",
};

const oracleShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "field-service",
    slug: "oracle-field-service",
    productName: "Oracle Field Service",
    primarySourceUrl: "https://www.oracle.com/a/ocom/docs/corporate/pricing/oracle-fusion-cloud-global-price-list.pdf",
    evidenceIds: ["oracle-field-service-catalog"],
  }),
  extraSeatAmount: null,
  extraSeatAmountStatus: "NOT_APPLICABLE",
  requiredAddonAmount: null,
  requiredAddonAmountStatus: "NOT_APPLICABLE",
  onboardingAmount: null,
  onboardingAmountStatus: "NOT_APPLICABLE",
  minimumSeats: 360,
  advertisedPlanName: "Oracle Fusion Field Service Cloud Service",
  advertisedAmount: 225,
  advertisedCadence: "MONTHLY",
  advertisedUnit: "USER",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Oracle Fusion Field Service Cloud Service",
  usableBaseAmount: null,
  usableCadence: null,
  usableUnit: "USER",
  usableStatus: "UNKNOWN",
  monthToMonthAmount: 225,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "NOT_APPLICABLE",
};

const justworksShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "payroll",
    slug: "justworks",
    productName: "Justworks",
    primarySourceUrl: "https://justworks.com/pricing",
    evidenceIds: ["justworks-pricing"],
  }),
  ...naAmount,
  advertisedPlanName: "PEO Basic",
  advertisedAmount: 79,
  advertisedCadence: "MONTHLY",
  advertisedUnit: "EMPLOYEE",
  advertisedStatus: "PUBLIC",
  usablePlanName: "PEO Basic",
  usableBaseAmount: 79,
  usableCadence: "MONTHLY",
  usableUnit: "EMPLOYEE",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 79,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "PEO",
};

const deelShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "payroll",
    slug: "deel",
    productName: "Deel",
    primarySourceUrl: "https://www.deel.com/pricing",
    evidenceIds: ["deel-pricing"],
  }),
  ...naAmount,
  advertisedPlanName: "Contractors",
  advertisedAmount: 49,
  advertisedCadence: "MONTHLY",
  advertisedUnit: "EMPLOYEE",
  advertisedStatus: "PUBLIC",
  usablePlanName: "US PEO",
  usableBaseAmount: 125,
  usableCadence: "MONTHLY",
  usableUnit: "EMPLOYEE",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 125,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "PEO",
};

const clockifyLikeTt = {
  toggl: pair(
    {
      ...identity({
        category: "time-tracking",
        slug: "toggl",
        productName: "Toggl Track",
        primarySourceUrl: "https://toggl.com/pricing",
        evidenceIds: ["toggl-pricing"],
      }),
      ...naAmount,
      advertisedPlanName: "Free",
      advertisedAmount: 0,
      advertisedCadence: "FREE",
      advertisedUnit: "USER",
      advertisedStatus: "PUBLIC",
      usablePlanName: "Starter",
      usableBaseAmount: 9,
      usableCadence: "ANNUAL_BILLED_MONTHLY",
      usableUnit: "USER",
      usableStatus: "PUBLIC",
      monthToMonthAmount: 12,
      monthToMonthAmountStatus: "PUBLIC",
      includedSeats: 3,
      contractTerm: "NOT_DISCLOSED",
      payrollServiceClass: "NOT_APPLICABLE",
    },
    ["tt-5", "tt-10"],
  ),
};

const harvestShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "time-tracking",
    slug: "harvest",
    productName: "Harvest",
    primarySourceUrl: "https://www.getharvest.com/pricing",
    evidenceIds: ["harvest-pricing"],
  }),
  ...naAmount,
  advertisedPlanName: "Free",
  advertisedAmount: 0,
  advertisedCadence: "FREE",
  advertisedUnit: "USER",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Teams",
  usableBaseAmount: 9,
  usableCadence: "ANNUAL_BILLED_MONTHLY",
  usableUnit: "USER",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 11,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: 1,
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "NOT_APPLICABLE",
};

const timeDoctorShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "time-tracking",
    slug: "time-doctor",
    productName: "Time Doctor",
    primarySourceUrl: "https://www.timedoctor.com/pricing",
    evidenceIds: ["time-doctor-pricing"],
  }),
  ...naAmount,
  advertisedPlanName: "Basic",
  advertisedAmount: 6.67,
  advertisedCadence: "ANNUAL_BILLED_MONTHLY",
  advertisedUnit: "USER",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Basic",
  usableBaseAmount: 6.67,
  usableCadence: "ANNUAL_BILLED_MONTHLY",
  usableUnit: "USER",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 8,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "NOT_APPLICABLE",
};

const rescueTimeShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "time-tracking",
    slug: "rescuetime",
    productName: "RescueTime",
    primarySourceUrl: "https://www.rescuetime.com/pricing",
    evidenceIds: ["rescuetime-pricing"],
  }),
  ...naAmount,
  advertisedPlanName: "Focus",
  advertisedAmount: 7,
  advertisedCadence: "ANNUAL_BILLED_MONTHLY",
  advertisedUnit: "USER",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Team Timesheets",
  usableBaseAmount: 16,
  usableCadence: "ANNUAL_BILLED_MONTHLY",
  usableUnit: "USER",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 18,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "NOT_APPLICABLE",
};

const everhourTt5: Draft = {
  ...identity({
    category: "time-tracking",
    slug: "everhour",
    productName: "Everhour",
    primarySourceUrl: "https://everhour.com/pricing",
    evidenceIds: ["everhour-pricing"],
  }),
  ...naAmount,
  scenarioId: "tt-5",
  advertisedPlanName: "Free",
  advertisedAmount: 0,
  advertisedCadence: "FREE",
  advertisedUnit: "USER",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Free",
  usableBaseAmount: 0,
  usableCadence: "FREE",
  usableUnit: "USER",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 0,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: 5,
  contractTerm: "MONTHLY",
  payrollServiceClass: "NOT_APPLICABLE",
};

const everhourTt10: Draft = {
  ...identity({
    category: "time-tracking",
    slug: "everhour",
    productName: "Everhour",
    primarySourceUrl: "https://everhour.com/pricing",
    evidenceIds: ["everhour-pricing"],
  }),
  extraSeatAmount: null,
  extraSeatAmountStatus: "NOT_APPLICABLE",
  requiredAddonAmount: null,
  requiredAddonAmountStatus: "NOT_APPLICABLE",
  onboardingAmount: null,
  onboardingAmountStatus: "NOT_APPLICABLE",
  minimumSeats: 5,
  scenarioId: "tt-10",
  advertisedPlanName: "Free",
  advertisedAmount: 0,
  advertisedCadence: "FREE",
  advertisedUnit: "USER",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Team",
  usableBaseAmount: 8.5,
  usableCadence: "ANNUAL_BILLED_MONTHLY",
  usableUnit: "USER",
  usableStatus: "PUBLIC",
  monthToMonthAmount: null,
  monthToMonthAmountStatus: "NOT_DISCLOSED",
  includedSeats: null,
  contractTerm: "ANNUAL",
  payrollServiceClass: "NOT_APPLICABLE",
};

const timelyTt5: Draft = {
  ...identity({
    category: "time-tracking",
    slug: "timely",
    productName: "Timely",
    primarySourceUrl: "https://memory.ai/timely/pricing",
    evidenceIds: ["timely-pricing"],
  }),
  ...naAmount,
  scenarioId: "tt-5",
  advertisedPlanName: "Starter",
  advertisedAmount: 9,
  advertisedCadence: "ANNUAL_BILLED_MONTHLY",
  advertisedUnit: "USER",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Starter",
  usableBaseAmount: 9,
  usableCadence: "ANNUAL_BILLED_MONTHLY",
  usableUnit: "USER",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 11,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: 5,
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "NOT_APPLICABLE",
};

const timelyTt10: Draft = {
  ...identity({
    category: "time-tracking",
    slug: "timely",
    productName: "Timely",
    primarySourceUrl: "https://memory.ai/timely/pricing",
    evidenceIds: ["timely-pricing"],
  }),
  ...naAmount,
  scenarioId: "tt-10",
  advertisedPlanName: "Starter",
  advertisedAmount: 9,
  advertisedCadence: "ANNUAL_BILLED_MONTHLY",
  advertisedUnit: "USER",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Premium",
  usableBaseAmount: 16,
  usableCadence: "ANNUAL_BILLED_MONTHLY",
  usableUnit: "USER",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 20,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: 50,
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "NOT_APPLICABLE",
};

const appointySched5: Draft = {
  ...identity({
    category: "scheduling",
    slug: "appointy",
    productName: "Appointy",
    primarySourceUrl: "https://www.appointy.com/pricing",
    evidenceIds: ["appointy-pricing"],
  }),
  extraSeatAmount: 5,
  extraSeatAmountStatus: "PUBLIC",
  requiredAddonAmount: null,
  requiredAddonAmountStatus: "NOT_APPLICABLE",
  onboardingAmount: null,
  onboardingAmountStatus: "NOT_APPLICABLE",
  minimumSeats: null,
  scenarioId: "sched-5",
  advertisedPlanName: "Free",
  advertisedAmount: 0,
  advertisedCadence: "FREE",
  advertisedUnit: "STAFF_CALENDAR",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Growth",
  usableBaseAmount: 19.99,
  usableCadence: "ANNUAL_BILLED_MONTHLY",
  usableUnit: "INCLUDED_CAP",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 29.99,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: 1,
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "NOT_APPLICABLE",
};

const simplybookSched5: Draft = {
  ...identity({
    category: "scheduling",
    slug: "simplybookme",
    productName: "SimplyBook.me",
    primarySourceUrl: "https://simplybook.me/en/pricing",
    evidenceIds: ["simplybookme-pricing"],
  }),
  ...naAmount,
  scenarioId: "sched-5",
  advertisedPlanName: "Free",
  advertisedAmount: 0,
  advertisedCadence: "FREE",
  advertisedUnit: "STAFF_CALENDAR",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Basic",
  usableBaseAmount: null,
  usableCadence: null,
  usableUnit: "INCLUDED_CAP",
  usableStatus: "NOT_DISCLOSED",
  includedSeats: 5,
  monthToMonthAmount: null,
  monthToMonthAmountStatus: "NOT_DISCLOSED",
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "NOT_APPLICABLE",
};

export const remainingPricingRows: PricingResearchRow[] = [
  ...pair(zohoCrmShared, ["crm-5", "crm-10"]),
  ...crmSeat({
    slug: "pipedrive",
    productName: "Pipedrive",
    primarySourceUrl: "https://www.pipedrive.com/en/pricing",
    evidenceIds: ["pipedrive-pricing"],
    advertisedPlanName: "Lite",
    advertisedAmount: 14,
    advertisedCadence: "ANNUAL_BILLED_MONTHLY",
    advertisedUnit: "USER",
    usablePlanName: "Lite",
    usableBaseAmount: 14,
    usableCadence: "ANNUAL_BILLED_MONTHLY",
    monthToMonthAmount: 24,
    contractTerm: "NOT_DISCLOSED",
  }),
  ...crmSeat({
    slug: "monday-crm",
    productName: "Monday CRM",
    primarySourceUrl: "https://monday.com/pricing",
    evidenceIds: ["monday-crm-pricing"],
    advertisedPlanName: "Basic",
    advertisedAmount: 12,
    advertisedCadence: "ANNUAL_BILLED_MONTHLY",
    advertisedUnit: "USER",
    usablePlanName: "Basic",
    usableBaseAmount: 12,
    usableCadence: "ANNUAL_BILLED_MONTHLY",
    monthToMonthAmount: 18,
    contractTerm: "NOT_DISCLOSED",
  }),
  ...crmSeat({
    slug: "freshsales",
    productName: "Freshsales",
    primarySourceUrl: "https://www.freshworks.com/freshsales/pricing/",
    evidenceIds: ["freshsales-pricing"],
    advertisedPlanName: "Growth",
    advertisedAmount: 9,
    advertisedCadence: "ANNUAL_BILLED_MONTHLY",
    advertisedUnit: "USER",
    usablePlanName: "Growth",
    usableBaseAmount: 9,
    usableCadence: "ANNUAL_BILLED_MONTHLY",
    monthToMonthAmount: null,
    monthToMonthAmountStatus: "NOT_DISCLOSED",
    contractTerm: "NOT_DISCLOSED",
  }),
  ...crmSeat({
    slug: "copper",
    productName: "Copper",
    primarySourceUrl: "https://www.copper.com/pricing",
    evidenceIds: ["copper-pricing"],
    advertisedPlanName: "Basic",
    advertisedAmount: 23,
    advertisedCadence: "ANNUAL_BILLED_MONTHLY",
    advertisedUnit: "USER",
    usablePlanName: "Basic",
    usableBaseAmount: 23,
    usableCadence: "ANNUAL_BILLED_MONTHLY",
    monthToMonthAmount: 29,
    contractTerm: "NOT_DISCLOSED",
  }),
  ...crmSeat({
    slug: "close",
    productName: "Close",
    primarySourceUrl: "https://www.close.com/pricing",
    evidenceIds: ["close-pricing"],
    advertisedPlanName: "Solo",
    advertisedAmount: 19,
    advertisedCadence: "MONTHLY",
    advertisedUnit: "USER",
    usablePlanName: "Essentials",
    usableBaseAmount: 49,
    usableCadence: "MONTHLY",
    monthToMonthAmount: 49,
    contractTerm: "NOT_DISCLOSED",
  }),
  ...pair(
    undisclosedShared({
      category: "crm",
      slug: "keap",
      productName: "Keap",
      primarySourceUrl: "https://keap.com/pricing",
      evidenceIds: ["keap-pricing"],
    }),
    ["crm-5", "crm-10"],
  ),
  finish(housecall1to4),
  finish(housecall2to8),
  ...pair(
    {
      ...identity({
        category: "field-service",
        slug: "service-fusion",
        productName: "Service Fusion",
        primarySourceUrl: "https://www.servicefusion.com/pricing",
        evidenceIds: ["service-fusion-pricing"],
      }),
      ...naAmount,
      advertisedPlanName: "Starter",
      advertisedAmount: 208,
      advertisedCadence: "ANNUAL_BILLED_MONTHLY",
      advertisedUnit: "COMPANY",
      advertisedStatus: "PUBLIC",
      usablePlanName: "Starter",
      usableBaseAmount: 208,
      usableCadence: "ANNUAL_BILLED_MONTHLY",
      usableUnit: "COMPANY",
      usableStatus: "PUBLIC",
      monthToMonthAmount: 245,
      monthToMonthAmountStatus: "PUBLIC",
      includedSeats: null,
      contractTerm: "MONTHLY",
      payrollServiceClass: "NOT_APPLICABLE",
    },
    ["fsm-1-4", "fsm-2-8"],
  ),
  ...pair(
    quoteShared({
      category: "field-service",
      slug: "workiz",
      productName: "Workiz",
      primarySourceUrl: "https://www.workiz.com/pricing-plans/",
      evidenceIds: ["workiz-pricing"],
    }),
    ["fsm-1-4", "fsm-2-8"],
  ),
  finish(kickserv1to4),
  finish(kickserv2to8),
  ...pair(
    {
      ...identity({
        category: "field-service",
        slug: "servicem8",
        productName: "ServiceM8",
        primarySourceUrl: "https://www.servicem8.com/pricing",
        evidenceIds: ["servicem8-pricing"],
      }),
      ...naAmount,
      advertisedPlanName: "Free",
      advertisedAmount: 0,
      advertisedCadence: "FREE",
      advertisedUnit: "FREE",
      advertisedStatus: "PUBLIC",
      usablePlanName: "Starter",
      usableBaseAmount: 29,
      usableCadence: "MONTHLY",
      usableUnit: "COMPANY",
      usableStatus: "PUBLIC",
      monthToMonthAmount: 29,
      monthToMonthAmountStatus: "PUBLIC",
      includedSeats: null,
      contractTerm: "MONTHLY",
      payrollServiceClass: "NOT_APPLICABLE",
    },
    ["fsm-1-4", "fsm-2-8"],
  ),
  ...pair(
    quoteShared({
      category: "field-service",
      slug: "fieldedge",
      productName: "FieldEdge",
      primarySourceUrl: "https://fieldedge.com/pricing",
      evidenceIds: ["fieldedge-pricing"],
    }),
    ["fsm-1-4", "fsm-2-8"],
  ),
  finish(mhelpdesk1to4),
  finish(mhelpdesk2to8),
  ...pair(
    quoteShared({
      category: "field-service",
      slug: "fieldpulse",
      productName: "FieldPulse",
      primarySourceUrl: "https://www.fieldpulse.com/pricing",
      evidenceIds: ["fieldpulse-pricing"],
    }),
    ["fsm-1-4", "fsm-2-8"],
  ),
  ...pair(
    quoteShared({
      category: "field-service",
      slug: "servicetrade",
      productName: "ServiceTrade",
      primarySourceUrl: "https://servicetrade.com/pricing/",
      evidenceIds: ["servicetrade-pricing"],
    }),
    ["fsm-1-4", "fsm-2-8"],
  ),
  ...pair(
    undisclosedShared({
      category: "field-service",
      slug: "workwave-service",
      productName: "WorkWave Service",
      primarySourceUrl: "https://www.workwave.com/service",
      evidenceIds: ["workwave-service-pricing"],
    }),
    ["fsm-1-4", "fsm-2-8"],
  ),
  ...pair(
    quoteShared({
      category: "field-service",
      slug: "buildops",
      productName: "BuildOps",
      primarySourceUrl: "https://buildops.com/pricing",
      evidenceIds: ["buildops-pricing"],
    }),
    ["fsm-1-4", "fsm-2-8"],
  ),
  ...pair(connecteamShared, ["fsm-1-4", "fsm-2-8"]),
  ...pair(oracleShared, ["fsm-1-4", "fsm-2-8"]),
  ...pair(
    quoteShared({
      category: "field-service",
      slug: "simpro",
      productName: "Simpro",
      primarySourceUrl: "https://www.simprogroup.com/pricing",
      evidenceIds: ["simpro-pricing"],
    }),
    ["fsm-1-4", "fsm-2-8"],
  ),
  ...pair(
    quoteShared({
      category: "field-service",
      slug: "zuper",
      productName: "Zuper",
      primarySourceUrl: "https://www.zuper.co",
      evidenceIds: ["zuper-pricing"],
    }),
    ["fsm-1-4", "fsm-2-8"],
  ),
  ...payrollBasePlus({
    slug: "quickbooks-payroll",
    productName: "QuickBooks Payroll",
    primarySourceUrl: "https://quickbooks.intuit.com/online/starting-up/payroll/",
    evidenceIds: ["quickbooks-payroll-pricing"],
    advertisedPlanName: "Workforce Payroll",
    advertisedAmount: 50,
    usablePlanName: "Workforce Payroll",
    usableBaseAmount: 50,
    extraSeatAmount: 7,
    payrollServiceClass: "FULL_SERVICE",
  }),
  ...payrollBasePlus({
    slug: "onpay",
    productName: "OnPay",
    primarySourceUrl: "https://onpay.com/payroll",
    evidenceIds: ["onpay-pricing"],
    advertisedPlanName: "Payroll",
    advertisedAmount: 49,
    usablePlanName: "Payroll",
    usableBaseAmount: 49,
    extraSeatAmount: 6,
    payrollServiceClass: "FULL_SERVICE",
  }),
  ...pair(
    quoteShared({
      category: "payroll",
      slug: "adp",
      productName: "ADP",
      primarySourceUrl: "https://www.adp.com/small-business",
      evidenceIds: ["adp-pricing"],
      payrollServiceClass: "FULL_SERVICE",
    }),
    ["payroll-5", "payroll-10"],
  ),
  ...pair(
    quoteShared({
      category: "payroll",
      slug: "paychex",
      productName: "Paychex",
      primarySourceUrl: "https://www.paychex.com/payroll",
      evidenceIds: ["paychex-pricing"],
      payrollServiceClass: "FULL_SERVICE",
    }),
    ["payroll-5", "payroll-10"],
  ),
  ...pair(
    quoteShared({
      category: "payroll",
      slug: "rippling",
      productName: "Rippling",
      primarySourceUrl: "https://www.rippling.com/pricing",
      evidenceIds: ["rippling-pricing"],
      payrollServiceClass: "FULL_SERVICE",
    }),
    ["payroll-5", "payroll-10"],
  ),
  ...payrollBasePlus({
    slug: "square-payroll",
    productName: "Square Payroll",
    primarySourceUrl: "https://squareup.com/us/en/payroll/pricing",
    evidenceIds: ["square-payroll-pricing"],
    advertisedPlanName: "Full-service payroll",
    advertisedAmount: 35,
    usablePlanName: "Full-service payroll",
    usableBaseAmount: 35,
    extraSeatAmount: 6,
    payrollServiceClass: "FULL_SERVICE",
    contractTerm: "MONTHLY",
  }),
  ...pair(justworksShared, ["payroll-5", "payroll-10"]),
  ...pair(deelShared, ["payroll-5", "payroll-10"]),
  ...payrollBasePlus({
    slug: "surepayroll",
    productName: "SurePayroll",
    primarySourceUrl: "https://www.surepayroll.com/pricing",
    evidenceIds: ["surepayroll-pricing"],
    advertisedPlanName: "Full Service",
    advertisedAmount: 39,
    usablePlanName: "Full Service",
    usableBaseAmount: 39,
    extraSeatAmount: 7,
    payrollServiceClass: "FULL_SERVICE",
    requiredAddonFor5: (50 + 5 * 5) / 12,
    requiredAddonFor10: (50 + 5 * 10) / 12,
  }),
  ...payrollBasePlus({
    slug: "wave",
    productName: "Wave",
    primarySourceUrl: "https://www.waveapps.com/payroll",
    evidenceIds: ["wave-payroll-pricing"],
    advertisedPlanName: "Payroll",
    advertisedAmount: 40,
    usablePlanName: "Payroll",
    usableBaseAmount: 40,
    extraSeatAmount: 6,
    payrollServiceClass: "FULL_SERVICE",
  }),
  finish({
    ...identity({
      category: "invoicing",
      slug: "quickbooks",
      productName: "QuickBooks",
      primarySourceUrl: "https://quickbooks.intuit.com/solopreneur/",
      evidenceIds: ["quickbooks-invoicing-pricing"],
    }),
    ...naAmount,
    scenarioId: "inv-5",
    advertisedPlanName: "Solopreneur",
    advertisedAmount: 20,
    advertisedCadence: "MONTHLY",
    advertisedUnit: "COMPANY",
    advertisedStatus: "PUBLIC",
    usablePlanName: "Solopreneur",
    usableBaseAmount: 20,
    usableCadence: "MONTHLY",
    usableUnit: "COMPANY",
    usableStatus: "PUBLIC",
    monthToMonthAmount: 20,
    monthToMonthAmountStatus: "PUBLIC",
    includedSeats: null,
    contractTerm: "MONTHLY",
    payrollServiceClass: "NOT_APPLICABLE",
  }),
  finish({
    ...identity({
      category: "invoicing",
      slug: "zoho-invoice",
      productName: "Zoho Invoice",
      primarySourceUrl: "https://www.zoho.com/invoice/pricing/",
      evidenceIds: ["zoho-invoice-pricing"],
    }),
    ...naAmount,
    scenarioId: "inv-5",
    advertisedPlanName: "Free",
    advertisedAmount: 0,
    advertisedCadence: "FREE",
    advertisedUnit: "COMPANY",
    advertisedStatus: "PUBLIC",
    usablePlanName: "Free",
    usableBaseAmount: 0,
    usableCadence: "FREE",
    usableUnit: "COMPANY",
    usableStatus: "PUBLIC",
    monthToMonthAmount: 0,
    monthToMonthAmountStatus: "PUBLIC",
    includedSeats: null,
    contractTerm: "MONTHLY",
    payrollServiceClass: "NOT_APPLICABLE",
  }),
  finish({
    ...identity({
      category: "invoicing",
      slug: "xero",
      productName: "Xero",
      primarySourceUrl: "https://www.xero.com/us/pricing",
      evidenceIds: ["xero-pricing"],
    }),
    ...naAmount,
    scenarioId: "inv-5",
    advertisedPlanName: "Early",
    advertisedAmount: 25,
    advertisedCadence: "MONTHLY",
    advertisedUnit: "COMPANY",
    advertisedStatus: "PUBLIC",
    usablePlanName: "Early",
    usableBaseAmount: 25,
    usableCadence: "MONTHLY",
    usableUnit: "COMPANY",
    usableStatus: "PUBLIC",
    monthToMonthAmount: 25,
    monthToMonthAmountStatus: "PUBLIC",
    includedSeats: null,
    contractTerm: "MONTHLY",
    payrollServiceClass: "NOT_APPLICABLE",
  }),
  finish({
    ...identity({
      category: "invoicing",
      slug: "invoice-ninja",
      productName: "Invoice Ninja",
      primarySourceUrl: "https://invoiceninja.com/pricing-plans/",
      evidenceIds: ["invoice-ninja-pricing"],
    }),
    ...naAmount,
    scenarioId: "inv-5",
    advertisedPlanName: "Free",
    advertisedAmount: 0,
    advertisedCadence: "FREE",
    advertisedUnit: "COMPANY",
    advertisedStatus: "PUBLIC",
    usablePlanName: "Free",
    usableBaseAmount: 0,
    usableCadence: "FREE",
    usableUnit: "COMPANY",
    usableStatus: "PUBLIC",
    monthToMonthAmount: 0,
    monthToMonthAmountStatus: "PUBLIC",
    includedSeats: null,
    contractTerm: "MONTHLY",
    payrollServiceClass: "NOT_APPLICABLE",
  }),
  finish({
    ...identity({
      category: "invoicing",
      slug: "honeybook",
      productName: "HoneyBook",
      primarySourceUrl: "https://www.honeybook.com/pricing",
      evidenceIds: ["honeybook-pricing"],
    }),
    ...naAmount,
    scenarioId: "inv-5",
    advertisedPlanName: "Starter",
    advertisedAmount: 29,
    advertisedCadence: "ANNUAL_BILLED_MONTHLY",
    advertisedUnit: "COMPANY",
    advertisedStatus: "PUBLIC",
    usablePlanName: "Starter",
    usableBaseAmount: 29,
    usableCadence: "ANNUAL_BILLED_MONTHLY",
    usableUnit: "COMPANY",
    usableStatus: "PUBLIC",
    monthToMonthAmount: 36,
    monthToMonthAmountStatus: "PUBLIC",
    includedSeats: null,
    contractTerm: "MONTHLY",
    payrollServiceClass: "NOT_APPLICABLE",
  }),
  finish({
    ...identity({
      category: "invoicing",
      slug: "bonsai",
      productName: "Bonsai",
      primarySourceUrl: "https://www.hellobonsai.com/pricing",
      evidenceIds: ["bonsai-pricing"],
    }),
    ...naAmount,
    scenarioId: "inv-5",
    advertisedPlanName: "Basic",
    advertisedAmount: 9,
    advertisedCadence: "ANNUAL_BILLED_MONTHLY",
    advertisedUnit: "COMPANY",
    advertisedStatus: "PUBLIC",
    usablePlanName: "Essentials",
    usableBaseAmount: 19,
    usableCadence: "ANNUAL_BILLED_MONTHLY",
    usableUnit: "COMPANY",
    usableStatus: "PUBLIC",
    monthToMonthAmount: 25,
    monthToMonthAmountStatus: "PUBLIC",
    includedSeats: null,
    contractTerm: "NOT_DISCLOSED",
    payrollServiceClass: "NOT_APPLICABLE",
  }),
  finish({
    ...identity({
      category: "scheduling",
      slug: "acuity-scheduling",
      productName: "Acuity Scheduling",
      primarySourceUrl: "https://www.acuityscheduling.com/pricing",
      evidenceIds: ["acuity-scheduling-pricing"],
    }),
    ...naAmount,
    scenarioId: "sched-5",
    advertisedPlanName: "Starter",
    advertisedAmount: 16,
    advertisedCadence: "ANNUAL_BILLED_MONTHLY",
    advertisedUnit: "INCLUDED_CAP",
    advertisedStatus: "PUBLIC",
    usablePlanName: "Standard",
    usableBaseAmount: 27,
    usableCadence: "ANNUAL_BILLED_MONTHLY",
    usableUnit: "INCLUDED_CAP",
    usableStatus: "PUBLIC",
    monthToMonthAmount: 34,
    monthToMonthAmountStatus: "PUBLIC",
    includedSeats: 6,
    contractTerm: "NOT_DISCLOSED",
    payrollServiceClass: "NOT_APPLICABLE",
  }),
  finish({
    ...identity({
      category: "scheduling",
      slug: "youcanbookme",
      productName: "YouCanBook.me",
      primarySourceUrl: "https://youcanbook.me/pricing",
      evidenceIds: ["youcanbookme-pricing"],
    }),
    ...naAmount,
    scenarioId: "sched-5",
    advertisedPlanName: "Free",
    advertisedAmount: 0,
    advertisedCadence: "FREE",
    advertisedUnit: "STAFF_CALENDAR",
    advertisedStatus: "PUBLIC",
    usablePlanName: "Team",
    usableBaseAmount: 16.2,
    usableCadence: "ANNUAL_BILLED_MONTHLY",
    usableUnit: "STAFF_CALENDAR",
    usableStatus: "PUBLIC",
    monthToMonthAmount: 18,
    monthToMonthAmountStatus: "PUBLIC",
    includedSeats: null,
    contractTerm: "NOT_DISCLOSED",
    payrollServiceClass: "NOT_APPLICABLE",
  }),
  finish({
    ...identity({
      category: "scheduling",
      slug: "setmore",
      productName: "Setmore",
      primarySourceUrl: "https://www.setmore.com/pricing",
      evidenceIds: ["setmore-pricing"],
    }),
    ...naAmount,
    scenarioId: "sched-5",
    advertisedPlanName: "Free",
    advertisedAmount: 0,
    advertisedCadence: "FREE",
    advertisedUnit: "STAFF_CALENDAR",
    advertisedStatus: "PUBLIC",
    usablePlanName: "Pro",
    usableBaseAmount: 5,
    usableCadence: "ANNUAL_BILLED_MONTHLY",
    usableUnit: "STAFF_CALENDAR",
    usableStatus: "PUBLIC",
    monthToMonthAmount: 12,
    monthToMonthAmountStatus: "PUBLIC",
    includedSeats: null,
    contractTerm: "NOT_DISCLOSED",
    payrollServiceClass: "NOT_APPLICABLE",
  }),
  finish(simplybookSched5),
  finish(appointySched5),
  finish({
    ...identity({
      category: "scheduling",
      slug: "zoho-bookings",
      productName: "Zoho Bookings",
      primarySourceUrl: "https://www.zoho.com/bookings/pricing.html",
      evidenceIds: ["zoho-bookings-pricing"],
    }),
    ...naAmount,
    scenarioId: "sched-5",
    advertisedPlanName: "Forever Free",
    advertisedAmount: 0,
    advertisedCadence: "FREE",
    advertisedUnit: "STAFF_CALENDAR",
    advertisedStatus: "PUBLIC",
    usablePlanName: "Basic",
    usableBaseAmount: 6,
    usableCadence: "ANNUAL_BILLED_MONTHLY",
    usableUnit: "STAFF_CALENDAR",
    usableStatus: "PUBLIC",
    monthToMonthAmount: 8,
    monthToMonthAmountStatus: "PUBLIC",
    includedSeats: null,
    contractTerm: "NOT_DISCLOSED",
    payrollServiceClass: "NOT_APPLICABLE",
  }),
  ...clockifyLikeTt.toggl,
  ...pair(harvestShared, ["tt-5", "tt-10"]),
  ...pair(timeDoctorShared, ["tt-5", "tt-10"]),
  ...pair(rescueTimeShared, ["tt-5", "tt-10"]),
  finish(everhourTt5),
  finish(everhourTt10),
  finish(timelyTt5),
  finish(timelyTt10),
];
