import { finish, identity, naAmount, pair, type Draft } from "./builders";
import { remainingPricingRows } from "./remainingRows";
import type {
  AmountStatus,
  Cadence,
  ContractTerm,
  PayrollServiceClass,
  PricingResearchRow,
  PricingUnit,
} from "./types";

const hubspotShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "crm",
    slug: "hubspot",
    productName: "HubSpot",
    primarySourceUrl: "https://legal.hubspot.com/hubspot-product-and-services-catalog",
    evidenceIds: ["hubspot-catalog", "hubspot-crm-product"],
  }),
  ...naAmount,
  advertisedPlanName: "Free Tools",
  advertisedAmount: 0,
  advertisedCadence: "FREE",
  advertisedUnit: "FREE",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Sales Hub Starter",
  usableBaseAmount: 20,
  usableCadence: "MONTHLY",
  usableUnit: "USER",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 20,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "NOT_APPLICABLE",
};

const salesforceShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "crm",
    slug: "salesforce",
    productName: "Salesforce",
    primarySourceUrl: "https://www.salesforce.com/editions-pricing/sales-cloud/",
    evidenceIds: ["salesforce-editions-pricing"],
  }),
  ...naAmount,
  advertisedPlanName: "Free Suite (conflicted with trial FAQ)",
  advertisedAmount: null,
  advertisedCadence: null,
  advertisedUnit: "NOT_APPLICABLE",
  advertisedStatus: "SOURCE_CONFLICT",
  usablePlanName: "Starter Suite",
  usableBaseAmount: 25,
  usableCadence: "MONTHLY",
  usableUnit: "USER",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 25,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "NOT_APPLICABLE",
};

const jobberAdvertised = {
  advertisedPlanName: "Core",
  advertisedAmount: 29,
  advertisedCadence: "ANNUAL_BILLED_MONTHLY" as Cadence,
  advertisedUnit: "INCLUDED_CAP" as PricingUnit,
  advertisedStatus: "PUBLIC" as AmountStatus,
  monthToMonthAmount: 49,
  monthToMonthAmountStatus: "PUBLIC" as AmountStatus,
  contractTerm: "MONTHLY" as ContractTerm,
  payrollServiceClass: "NOT_APPLICABLE" as PayrollServiceClass,
};

const jobber1to4: Draft = {
  ...identity({
    category: "field-service",
    slug: "jobber",
    productName: "Jobber",
    primarySourceUrl: "https://www.getjobber.com/pricing",
    evidenceIds: ["jobber-pricing", "jobber-connect-help"],
  }),
  ...naAmount,
  ...jobberAdvertised,
  scenarioId: "fsm-1-4",
  usablePlanName: "Connect",
  usableBaseAmount: null,
  usableCadence: null,
  usableUnit: "INCLUDED_CAP",
  usableStatus: "UNKNOWN",
  includedSeats: 5,
  extraSeatAmount: null,
  extraSeatAmountStatus: "NOT_DISCLOSED",
};

const jobber2to8: Draft = {
  ...identity({
    category: "field-service",
    slug: "jobber",
    productName: "Jobber",
    primarySourceUrl: "https://www.getjobber.com/pricing",
    evidenceIds: ["jobber-pricing", "jobber-grow-help"],
  }),
  ...naAmount,
  ...jobberAdvertised,
  scenarioId: "fsm-2-8",
  usablePlanName: "Grow",
  usableBaseAmount: null,
  usableCadence: null,
  usableUnit: "INCLUDED_CAP",
  usableStatus: "UNKNOWN",
  includedSeats: 10,
  extraSeatAmount: null,
  extraSeatAmountStatus: "NOT_DISCLOSED",
};

const serviceTitanShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "field-service",
    slug: "servicetitan",
    productName: "ServiceTitan",
    primarySourceUrl: "https://www.servicetitan.com/pricing",
    evidenceIds: ["servicetitan-pricing"],
  }),
  ...naAmount,
  advertisedPlanName: null,
  advertisedAmount: null,
  advertisedCadence: null,
  advertisedUnit: "QUOTE",
  advertisedStatus: "QUOTE_REQUIRED",
  usablePlanName: null,
  usableBaseAmount: null,
  usableCadence: null,
  usableUnit: "QUOTE",
  usableStatus: "QUOTE_REQUIRED",
  monthToMonthAmount: null,
  monthToMonthAmountStatus: "NOT_APPLICABLE",
  includedSeats: null,
  contractTerm: "QUOTE",
  payrollServiceClass: "NOT_APPLICABLE",
};

const gustoShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "payroll",
    slug: "gusto",
    productName: "Gusto",
    primarySourceUrl: "https://gusto.com/product/pricing",
    evidenceIds: ["gusto-pricing"],
  }),
  extraSeatAmount: 6,
  extraSeatAmountStatus: "PUBLIC",
  requiredAddonAmount: null,
  requiredAddonAmountStatus: "NOT_APPLICABLE",
  onboardingAmount: null,
  onboardingAmountStatus: "NOT_APPLICABLE",
  minimumSeats: null,
  advertisedPlanName: "Simple",
  advertisedAmount: 49,
  advertisedCadence: "MONTHLY",
  advertisedUnit: "BASE_PLUS_UNIT",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Simple",
  usableBaseAmount: 49,
  usableCadence: "MONTHLY",
  usableUnit: "BASE_PLUS_UNIT",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 49,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "MONTHLY",
  payrollServiceClass: "FULL_SERVICE",
};

const patriotShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "payroll",
    slug: "patriot-payroll",
    productName: "Patriot Payroll",
    primarySourceUrl: "https://www.patriotsoftware.com/payroll/pricing/",
    evidenceIds: ["patriot-payroll-pricing"],
  }),
  extraSeatAmount: 5,
  extraSeatAmountStatus: "PUBLIC",
  requiredAddonAmount: null,
  requiredAddonAmountStatus: "NOT_APPLICABLE",
  onboardingAmount: null,
  onboardingAmountStatus: "NOT_APPLICABLE",
  minimumSeats: null,
  advertisedPlanName: "Basic Payroll",
  advertisedAmount: 17,
  advertisedCadence: "MONTHLY",
  advertisedUnit: "BASE_PLUS_UNIT",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Full Service Payroll",
  usableBaseAmount: 37,
  usableCadence: "MONTHLY",
  usableUnit: "BASE_PLUS_UNIT",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 37,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "NOT_DISCLOSED",
  payrollServiceClass: "FULL_SERVICE",
};

const freshbooksInv5: Draft = {
  ...identity({
    category: "invoicing",
    slug: "freshbooks",
    productName: "FreshBooks",
    primarySourceUrl: "https://www.freshbooks.com/pricing",
    evidenceIds: ["freshbooks-pricing"],
  }),
  ...naAmount,
  scenarioId: "inv-5",
  advertisedPlanName: "Lite",
  advertisedAmount: 23,
  advertisedCadence: "MONTHLY",
  advertisedUnit: "COMPANY",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Lite",
  usableBaseAmount: 23,
  usableCadence: "MONTHLY",
  usableUnit: "COMPANY",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 23,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "MONTHLY",
  payrollServiceClass: "NOT_APPLICABLE",
};

const waveInv5: Draft = {
  ...identity({
    category: "invoicing",
    slug: "wave",
    productName: "Wave",
    primarySourceUrl: "https://www.waveapps.com/pricing",
    evidenceIds: ["wave-pricing"],
  }),
  ...naAmount,
  scenarioId: "inv-5",
  advertisedPlanName: "Starter",
  advertisedAmount: 0,
  advertisedCadence: "FREE",
  advertisedUnit: "COMPANY",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Starter",
  usableBaseAmount: 0,
  usableCadence: "FREE",
  usableUnit: "COMPANY",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 0,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "MONTHLY",
  payrollServiceClass: "NOT_APPLICABLE",
};

const calendlySched5: Draft = {
  ...identity({
    category: "scheduling",
    slug: "calendly",
    productName: "Calendly",
    primarySourceUrl: "https://calendly.com/pricing",
    evidenceIds: ["calendly-pricing"],
  }),
  ...naAmount,
  scenarioId: "sched-5",
  advertisedPlanName: "Free",
  advertisedAmount: 0,
  advertisedCadence: "FREE",
  advertisedUnit: "STAFF_CALENDAR",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Standard",
  usableBaseAmount: 10,
  usableCadence: "ANNUAL_BILLED_MONTHLY",
  usableUnit: "STAFF_CALENDAR",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 12,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "MONTHLY",
  payrollServiceClass: "NOT_APPLICABLE",
};

const squareSched5: Draft = {
  ...identity({
    category: "scheduling",
    slug: "square-appointments",
    productName: "Square Appointments",
    primarySourceUrl: "https://squareup.com/us/en/appointments/pricing",
    evidenceIds: ["square-appointments-pricing"],
  }),
  ...naAmount,
  scenarioId: "sched-5",
  advertisedPlanName: "Square Free",
  advertisedAmount: 0,
  advertisedCadence: "FREE",
  advertisedUnit: "COMPANY",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Square Free",
  usableBaseAmount: 0,
  usableCadence: "FREE",
  usableUnit: "COMPANY",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 0,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "MONTHLY",
  payrollServiceClass: "NOT_APPLICABLE",
};

const clockifySharedBase: Omit<Draft, "scenarioId" | "usablePlanName" | "usableBaseAmount" | "usableCadence" | "usableUnit" | "usableStatus" | "monthToMonthAmount" | "monthToMonthAmountStatus"> =
  {
    ...identity({
      category: "time-tracking",
      slug: "clockify",
      productName: "Clockify",
      primarySourceUrl: "https://clockify.me/pricing",
      evidenceIds: ["clockify-pricing", "clockify-free-plan-help"],
    }),
    ...naAmount,
    advertisedPlanName: "Free",
    advertisedAmount: 0,
    advertisedCadence: "FREE",
    advertisedUnit: "USER",
    advertisedStatus: "PUBLIC",
    includedSeats: 5,
    contractTerm: "MONTHLY",
    payrollServiceClass: "NOT_APPLICABLE",
  };

const clockifyTt5: Draft = {
  ...clockifySharedBase,
  scenarioId: "tt-5",
  usablePlanName: "Free",
  usableBaseAmount: 0,
  usableCadence: "FREE",
  usableUnit: "USER",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 0,
  monthToMonthAmountStatus: "PUBLIC",
};

const clockifyTt10: Draft = {
  ...clockifySharedBase,
  scenarioId: "tt-10",
  usablePlanName: "Basic",
  usableBaseAmount: 3.99,
  usableCadence: "ANNUAL_BILLED_MONTHLY",
  usableUnit: "USER",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 4.99,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
};

const hubstaffShared: Omit<Draft, "scenarioId"> = {
  ...identity({
    category: "time-tracking",
    slug: "hubstaff",
    productName: "Hubstaff",
    primarySourceUrl: "https://hubstaff.com/pricing",
    evidenceIds: ["hubstaff-pricing"],
  }),
  extraSeatAmount: null,
  extraSeatAmountStatus: "NOT_APPLICABLE",
  requiredAddonAmount: null,
  requiredAddonAmountStatus: "NOT_APPLICABLE",
  onboardingAmount: null,
  onboardingAmountStatus: "NOT_APPLICABLE",
  minimumSeats: 2,
  advertisedPlanName: "Starter",
  advertisedAmount: 4.99,
  advertisedCadence: "ANNUAL_BILLED_MONTHLY",
  advertisedUnit: "USER",
  advertisedStatus: "PUBLIC",
  usablePlanName: "Starter",
  usableBaseAmount: 4.99,
  usableCadence: "ANNUAL_BILLED_MONTHLY",
  usableUnit: "USER",
  usableStatus: "PUBLIC",
  monthToMonthAmount: 7,
  monthToMonthAmountStatus: "PUBLIC",
  includedSeats: null,
  contractTerm: "MONTHLY",
  payrollServiceClass: "NOT_APPLICABLE",
};

export const pricingPilotRows: PricingResearchRow[] = [
  ...pair(hubspotShared, ["crm-5", "crm-10"]),
  ...pair(salesforceShared, ["crm-5", "crm-10"]),
  finish(jobber1to4),
  finish(jobber2to8),
  ...pair(serviceTitanShared, ["fsm-1-4", "fsm-2-8"]),
  ...pair(gustoShared, ["payroll-5", "payroll-10"]),
  ...pair(patriotShared, ["payroll-5", "payroll-10"]),
  finish(freshbooksInv5),
  finish(waveInv5),
  finish(calendlySched5),
  finish(squareSched5),
  finish(clockifyTt5),
  finish(clockifyTt10),
  ...pair(hubstaffShared, ["tt-5", "tt-10"]),
];

export const pricingResearchRows: PricingResearchRow[] = [
  ...pricingPilotRows,
  ...remainingPricingRows,
];

export const PILOT_PRODUCTS = [
  { category: "crm" as const, slug: "hubspot", productName: "HubSpot" },
  { category: "crm" as const, slug: "salesforce", productName: "Salesforce" },
  { category: "field-service" as const, slug: "jobber", productName: "Jobber" },
  { category: "field-service" as const, slug: "servicetitan", productName: "ServiceTitan" },
  { category: "payroll" as const, slug: "gusto", productName: "Gusto" },
  { category: "payroll" as const, slug: "patriot-payroll", productName: "Patriot Payroll" },
  { category: "invoicing" as const, slug: "freshbooks", productName: "FreshBooks" },
  { category: "invoicing" as const, slug: "wave", productName: "Wave" },
  { category: "scheduling" as const, slug: "calendly", productName: "Calendly" },
  { category: "scheduling" as const, slug: "square-appointments", productName: "Square Appointments" },
  { category: "time-tracking" as const, slug: "clockify", productName: "Clockify" },
  { category: "time-tracking" as const, slug: "hubstaff", productName: "Hubstaff" },
] as const;
