export type SearchItemType =
  | "Review"
  | "Comparison"
  | "Alternatives"
  | "Guide"
  | "Best Software"
  | "Best For"
  | "Category";

export type SearchIndexItem = {
  title: string;
  href: string;
  type: SearchItemType;
  category: string;
  entity?: string;
  keywords: string[];
};

/**
  * Local search index for BeltStack.
  *
  * This is intentionally small and focused on primary entities/topics:
  * - key reviews
  * - high-intent comparisons
  * - alternatives pages
  * - best-software roundups
  * - major best-for pages
  * - major guides
  * - category hubs
  *
  * In the future this can be generated automatically from hub data files.
  */
export const searchIndex: SearchIndexItem[] = [
  // ——— Category hubs ———
  {
    title: "Payroll Software",
    href: "/payroll",
    type: "Category",
    category: "Payroll",
    keywords: ["payroll", "payroll software", "contractor payroll", "trade payroll"],
  },
  {
    title: "Accounting Software",
    href: "/accounting",
    type: "Category",
    category: "Accounting",
    keywords: ["accounting", "bookkeeping", "contractor accounting"],
  },
  {
    title: "CRM Software",
    href: "/crm",
    type: "Category",
    category: "CRM",
    keywords: ["crm", "crm software", "customer management"],
  },
  {
    title: "Field Service Software",
    href: "/field-service",
    type: "Category",
    category: "Field Service",
    keywords: ["field service", "fsm", "hvac software", "plumbing software"],
  },
  {
    title: "Project Management Software",
    href: "/project-management",
    type: "Category",
    category: "Project Management",
    keywords: ["project management", "job management", "projects"],
  },
  {
    title: "Helpdesk Software",
    href: "/helpdesk",
    type: "Category",
    category: "Helpdesk",
    keywords: ["helpdesk", "support software", "ticketing"],
  },
  {
    title: "POS Software",
    href: "/pos",
    type: "Category",
    category: "POS",
    keywords: ["pos", "point of sale", "retail pos"],
  },
  {
    title: "Inventory Software",
    href: "/inventory",
    type: "Category",
    category: "Inventory",
    keywords: ["inventory", "inventory management", "stock tracking"],
  },
  {
    title: "Scheduling Software",
    href: "/scheduling",
    type: "Category",
    category: "Scheduling",
    keywords: ["scheduling", "appointment scheduling", "booking"],
  },
  {
    title: "Time Tracking Software",
    href: "/time-tracking",
    type: "Category",
    category: "Time Tracking",
    keywords: ["time tracking", "timesheets", "billable hours"],
  },
  {
    title: "HR Software",
    href: "/hr",
    type: "Category",
    category: "HR",
    keywords: ["hr", "hr software", "people ops"],
  },
  {
    title: "Invoicing Software",
    href: "/invoicing",
    type: "Category",
    category: "Invoicing",
    keywords: ["invoicing", "invoice software", "billing"],
  },
  {
    title: "Website Builders",
    href: "/website-builders",
    type: "Category",
    category: "Website Builders",
    keywords: ["website builders", "website builder", "small business website", "contractor website"],
  },
  {
    title: "Lead Generation Tools",
    href: "/lead-generation",
    type: "Category",
    category: "Lead Generation",
    keywords: ["lead generation", "local leads", "contractor leads", "home services leads", "thumbtack", "angi"],
  },
  {
    title: "SEO Tools",
    href: "/seo-tools",
    type: "Category",
    category: "SEO Tools",
    keywords: ["seo tools", "local seo", "semrush", "ahrefs", "google maps seo", "contractor seo"],
  },
  {
    title: "Call Tracking Software",
    href: "/call-tracking",
    type: "Category",
    category: "Call Tracking",
    keywords: ["call tracking", "callrail", "dynamic number insertion", "marketing attribution", "phone call tracking"],
  },
  {
    title: "Reputation Management Software",
    href: "/reputation-management",
    type: "Category",
    category: "Reputation Management",
    keywords: ["reputation management", "online reviews", "google reviews", "yelp reviews", "review management software"],
  },
  {
    title: "Email Marketing Software",
    href: "/email-marketing",
    type: "Category",
    category: "Email Marketing",
    keywords: ["email marketing", "email marketing software", "mailchimp", "contractor email marketing", "newsletter software"],
  },
  {
    title: "Payment Processing Software",
    href: "/payment-processing",
    type: "Category",
    category: "Payment Processing",
    keywords: ["payment processing", "stripe", "square", "credit card processing", "merchant services", "contractor payments"],
  },

  // ——— Reviews (popular entities) ———
  {
    title: "Gusto Review (2026)",
    href: "/payroll/review/gusto",
    type: "Review",
    category: "Payroll",
    entity: "Gusto",
    keywords: ["gusto", "gusto review", "gusto payroll"],
  },
  {
    title: "QuickBooks Online Review (2026)",
    href: "/accounting/review/quickbooks-online",
    type: "Review",
    category: "Accounting",
    entity: "QuickBooks Online",
    keywords: ["quickbooks", "quickbooks online", "quickbooks accounting"],
  },
  {
    title: "HubSpot CRM Review (2026)",
    href: "/crm/review/hubspot",
    type: "Review",
    category: "CRM",
    entity: "HubSpot",
    keywords: ["hubspot", "hubspot crm", "hubspot review"],
  },
  {
    title: "Zendesk Review (2026)",
    href: "/helpdesk/review/zendesk",
    type: "Review",
    category: "Helpdesk",
    entity: "Zendesk",
    keywords: ["zendesk", "zendesk review", "zendesk helpdesk"],
  },
  {
    title: "ServiceTitan Review (2026)",
    href: "/field-service/review/servicetitan",
    type: "Review",
    category: "Field Service",
    entity: "ServiceTitan",
    keywords: ["servicetitan", "servicetitan review", "field service software"],
  },
  {
    title: "Connecteam Review (2026)",
    href: "/field-service/review/connecteam",
    type: "Review",
    category: "Field Service",
    entity: "Connecteam",
    keywords: ["connecteam", "connecteam review", "deskless workforce", "field service software"],
  },
  {
    title: "Oracle Field Service Review (2026)",
    href: "/field-service/review/oracle-field-service",
    type: "Review",
    category: "Field Service",
    entity: "Oracle Field Service",
    keywords: ["oracle field service", "oracle field service review", "enterprise field service"],
  },
  {
    title: "Simpro Review (2026)",
    href: "/field-service/review/simpro",
    type: "Review",
    category: "Field Service",
    entity: "Simpro",
    keywords: ["simpro", "simpro review", "trade field service software"],
  },
  {
    title: "Zuper Review (2026)",
    href: "/field-service/review/zuper",
    type: "Review",
    category: "Field Service",
    entity: "Zuper",
    keywords: ["zuper", "zuper review", "field service software"],
  },
  {
    title: "Square Review (2026)",
    href: "/pos/review/square-pos",
    type: "Review",
    category: "POS",
    entity: "Square",
    keywords: ["square", "square pos", "square review"],
  },
  {
    title: "Thumbtack Review (2026)",
    href: "/lead-generation/review/thumbtack",
    type: "Review",
    category: "Lead Generation",
    entity: "Thumbtack",
    keywords: ["thumbtack", "thumbtack review", "thumbtack leads"],
  },
  {
    title: "Google Local Services Ads Review (2026)",
    href: "/lead-generation/review/google-local-services-ads",
    type: "Review",
    category: "Lead Generation",
    entity: "Google Local Services Ads",
    keywords: ["google lsa", "local services ads", "google screened leads"],
  },
  {
    title: "Semrush Review (2026)",
    href: "/seo-tools/review/semrush",
    type: "Review",
    category: "SEO Tools",
    entity: "Semrush",
    keywords: ["semrush", "semrush review", "seo software"],
  },
  {
    title: "Ahrefs Review (2026)",
    href: "/seo-tools/review/ahrefs",
    type: "Review",
    category: "SEO Tools",
    entity: "Ahrefs",
    keywords: ["ahrefs", "ahrefs review", "backlink tool"],
  },
  {
    title: "BrightLocal Review (2026)",
    href: "/seo-tools/review/brightlocal",
    type: "Review",
    category: "SEO Tools",
    entity: "BrightLocal",
    keywords: ["brightlocal", "brightlocal review", "local seo software"],
  },
  {
    title: "CallRail Review (2026)",
    href: "/call-tracking/review/callrail",
    type: "Review",
    category: "Call Tracking",
    entity: "CallRail",
    keywords: ["callrail", "callrail review", "call tracking"],
  },
  {
    title: "CallTrackingMetrics Review (2026)",
    href: "/call-tracking/review/calltrackingmetrics",
    type: "Review",
    category: "Call Tracking",
    entity: "CallTrackingMetrics",
    keywords: ["calltrackingmetrics", "ctm", "call tracking analytics"],
  },
  {
    title: "WhatConverts Review (2026)",
    href: "/call-tracking/review/whatconverts",
    type: "Review",
    category: "Call Tracking",
    entity: "WhatConverts",
    keywords: ["whatconverts", "whatconverts review", "lead tracking"],
  },
  {
    title: "Podium Review (2026)",
    href: "/reputation-management/review/podium",
    type: "Review",
    category: "Reputation Management",
    entity: "Podium",
    keywords: ["podium review", "podium reputation management", "review request software"],
  },
  {
    title: "Birdeye Review (2026)",
    href: "/reputation-management/review/birdeye",
    type: "Review",
    category: "Reputation Management",
    entity: "Birdeye",
    keywords: ["birdeye review", "birdeye reputation", "multi location reviews"],
  },
  {
    title: "Mailchimp Review (2026)",
    href: "/email-marketing/review/mailchimp",
    type: "Review",
    category: "Email Marketing",
    entity: "Mailchimp",
    keywords: ["mailchimp", "mailchimp review", "email marketing platform"],
  },
  {
    title: "ActiveCampaign Review (2026)",
    href: "/email-marketing/review/activecampaign",
    type: "Review",
    category: "Email Marketing",
    entity: "ActiveCampaign",
    keywords: ["activecampaign", "activecampaign review", "email automation software"],
  },
  {
    title: "Klaviyo Review (2026)",
    href: "/email-marketing/review/klaviyo",
    type: "Review",
    category: "Email Marketing",
    entity: "Klaviyo",
    keywords: ["klaviyo", "klaviyo review", "email marketing ecommerce"],
  },
  {
    title: "Stripe Review (2026)",
    href: "/payment-processing/review/stripe",
    type: "Review",
    category: "Payment Processing",
    entity: "Stripe",
    keywords: ["stripe", "stripe review", "stripe payments", "online payments"],
  },
  {
    title: "Square Review (2026)",
    href: "/payment-processing/review/square",
    type: "Review",
    category: "Payment Processing",
    entity: "Square",
    keywords: ["square", "square review", "square payments", "mobile card reader"],
  },

  // ——— Alternatives ———
  {
    title: "Best Gusto Alternatives (2026)",
    href: "/payroll/alternatives/gusto",
    type: "Alternatives",
    category: "Payroll",
    entity: "Gusto",
    keywords: ["gusto", "gusto alternatives", "payroll alternatives"],
  },
  {
    title: "Best QuickBooks Online Alternatives (2026)",
    href: "/accounting/alternatives/quickbooks-online",
    type: "Alternatives",
    category: "Accounting",
    entity: "QuickBooks Online",
    keywords: ["quickbooks", "quickbooks alternatives", "accounting alternatives"],
  },
  {
    title: "Best HubSpot Alternatives (2026)",
    href: "/crm/alternatives/hubspot",
    type: "Alternatives",
    category: "CRM",
    entity: "HubSpot",
    keywords: ["hubspot", "hubspot alternatives", "crm alternatives"],
  },
  {
    title: "Best Zendesk Alternatives (2026)",
    href: "/helpdesk/alternatives/zendesk",
    type: "Alternatives",
    category: "Helpdesk",
    entity: "Zendesk",
    keywords: ["zendesk", "zendesk alternatives", "helpdesk alternatives"],
  },
  {
    title: "Best ServiceTitan Alternatives (2026)",
    href: "/field-service/alternatives/servicetitan",
    type: "Alternatives",
    category: "Field Service",
    entity: "ServiceTitan",
    keywords: ["servicetitan", "servicetitan alternatives", "field service alternatives"],
  },
  {
    title: "Best Connecteam Alternatives (2026)",
    href: "/field-service/alternatives/connecteam",
    type: "Alternatives",
    category: "Field Service",
    entity: "Connecteam",
    keywords: ["connecteam", "connecteam alternatives", "field service alternatives"],
  },
  {
    title: "Best Oracle Field Service Alternatives (2026)",
    href: "/field-service/alternatives/oracle-field-service",
    type: "Alternatives",
    category: "Field Service",
    entity: "Oracle Field Service",
    keywords: ["oracle field service", "oracle field service alternatives", "field service alternatives"],
  },
  {
    title: "Best Simpro Alternatives (2026)",
    href: "/field-service/alternatives/simpro",
    type: "Alternatives",
    category: "Field Service",
    entity: "Simpro",
    keywords: ["simpro", "simpro alternatives", "field service alternatives"],
  },
  {
    title: "Best Zuper Alternatives (2026)",
    href: "/field-service/alternatives/zuper",
    type: "Alternatives",
    category: "Field Service",
    entity: "Zuper",
    keywords: ["zuper", "zuper alternatives", "field service alternatives"],
  },
  {
    title: "Best Square Alternatives (2026)",
    href: "/pos/alternatives/square-pos",
    type: "Alternatives",
    category: "POS",
    entity: "Square",
    keywords: ["square", "square alternatives", "pos alternatives"],
  },
  {
    title: "Best Thumbtack Alternatives (2026)",
    href: "/lead-generation/alternatives/thumbtack",
    type: "Alternatives",
    category: "Lead Generation",
    entity: "Thumbtack",
    keywords: ["thumbtack", "thumbtack alternatives", "lead gen alternatives"],
  },
  {
    title: "Best Angi Alternatives (2026)",
    href: "/lead-generation/alternatives/angi",
    type: "Alternatives",
    category: "Lead Generation",
    entity: "Angi",
    keywords: ["angi", "angi alternatives", "homeadvisor angi leads"],
  },
  {
    title: "Best HomeAdvisor Alternatives (2026)",
    href: "/lead-generation/alternatives/homeadvisor",
    type: "Alternatives",
    category: "Lead Generation",
    entity: "HomeAdvisor",
    keywords: ["homeadvisor", "homeadvisor alternatives", "home services leads"],
  },
  {
    title: "Best Semrush Alternatives (2026)",
    href: "/seo-tools/alternatives/semrush",
    type: "Alternatives",
    category: "SEO Tools",
    entity: "Semrush",
    keywords: ["semrush alternatives", "seo software alternatives"],
  },
  {
    title: "Best Ahrefs Alternatives (2026)",
    href: "/seo-tools/alternatives/ahrefs",
    type: "Alternatives",
    category: "SEO Tools",
    entity: "Ahrefs",
    keywords: ["ahrefs alternatives", "seo tools like ahrefs"],
  },
  {
    title: "Best Moz Pro Alternatives (2026)",
    href: "/seo-tools/alternatives/moz-pro",
    type: "Alternatives",
    category: "SEO Tools",
    entity: "Moz Pro",
    keywords: ["moz pro alternatives", "moz alternatives"],
  },
  {
    title: "Best CallRail Alternatives (2026)",
    href: "/call-tracking/alternatives/callrail",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "CallRail",
    keywords: ["callrail alternatives", "call tracking alternatives"],
  },
  {
    title: "Best Podium Alternatives (2026)",
    href: "/reputation-management/alternatives/podium",
    type: "Alternatives",
    category: "Reputation Management",
    entity: "Podium",
    keywords: ["podium alternatives", "reputation software alternatives"],
  },
  {
    title: "Best CallTrackingMetrics Alternatives (2026)",
    href: "/call-tracking/alternatives/calltrackingmetrics",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "CallTrackingMetrics",
    keywords: ["calltrackingmetrics alternatives", "ctm alternatives"],
  },
  {
    title: "Best WhatConverts Alternatives (2026)",
    href: "/call-tracking/alternatives/whatconverts",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "WhatConverts",
    keywords: ["whatconverts alternatives", "lead reporting alternatives"],
  },
  {
    title: "Best Ringba Alternatives (2026)",
    href: "/call-tracking/alternatives/ringba",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "Ringba",
    keywords: ["ringba alternatives", "pay per call software alternatives"],
  },
  {
    title: "Best Invoca Alternatives (2026)",
    href: "/call-tracking/alternatives/invoca",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "Invoca",
    keywords: ["invoca alternatives", "conversation intelligence alternatives"],
  },
  {
    title: "Best Twilio Alternatives (2026)",
    href: "/call-tracking/alternatives/twilio",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "Twilio",
    keywords: ["twilio alternatives", "programmable voice alternatives"],
  },
  {
    title: "Best PhoneWagon Alternatives (2026)",
    href: "/call-tracking/alternatives/phonewagon",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "PhoneWagon",
    keywords: ["phonewagon alternatives", "simple call tracking alternatives"],
  },
  {
    title: "Best Nimbata Alternatives (2026)",
    href: "/call-tracking/alternatives/nimbata",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "Nimbata",
    keywords: ["nimbata alternatives", "gdpr call tracking alternatives"],
  },
  {
    title: "Best Mailchimp Alternatives (2026)",
    href: "/email-marketing/alternatives/mailchimp",
    type: "Alternatives",
    category: "Email Marketing",
    entity: "Mailchimp",
    keywords: ["mailchimp alternatives", "email marketing alternatives"],
  },
  {
    title: "Best ActiveCampaign Alternatives (2026)",
    href: "/email-marketing/alternatives/activecampaign",
    type: "Alternatives",
    category: "Email Marketing",
    entity: "ActiveCampaign",
    keywords: ["activecampaign alternatives", "marketing automation alternatives"],
  },
  {
    title: "Best Klaviyo Alternatives (2026)",
    href: "/email-marketing/alternatives/klaviyo",
    type: "Alternatives",
    category: "Email Marketing",
    entity: "Klaviyo",
    keywords: ["klaviyo alternatives", "email segmentation alternatives"],
  },
  {
    title: "Best Constant Contact Alternatives (2026)",
    href: "/email-marketing/alternatives/constant-contact",
    type: "Alternatives",
    category: "Email Marketing",
    entity: "Constant Contact",
    keywords: ["constant contact alternatives", "email marketing alternatives"],
  },
  {
    title: "Best HubSpot Alternatives (2026)",
    href: "/email-marketing/alternatives/hubspot-email-marketing",
    type: "Alternatives",
    category: "Email Marketing",
    entity: "HubSpot",
    keywords: ["hubspot email marketing alternatives", "hubspot marketing hub alternatives"],
  },
  {
    title: "Best Kit Alternatives (2026)",
    href: "/email-marketing/alternatives/convertkit",
    type: "Alternatives",
    category: "Email Marketing",
    entity: "Kit",
    keywords: ["kit alternatives", "convertkit alternatives", "creator email alternatives"],
  },
  {
    title: "Best Brevo Alternatives (2026)",
    href: "/email-marketing/alternatives/brevo",
    type: "Alternatives",
    category: "Email Marketing",
    entity: "Brevo",
    keywords: ["brevo alternatives", "sendinblue alternatives", "email sms marketing alternatives"],
  },
  {
    title: "Best MailerLite Alternatives (2026)",
    href: "/email-marketing/alternatives/mailerlite",
    type: "Alternatives",
    category: "Email Marketing",
    entity: "MailerLite",
    keywords: ["mailerlite alternatives", "cheap email marketing alternatives"],
  },
  {
    title: "Best Stripe Alternatives (2026)",
    href: "/payment-processing/alternatives/stripe",
    type: "Alternatives",
    category: "Payment Processing",
    entity: "Stripe",
    keywords: ["stripe alternatives", "payment processing alternatives"],
  },
  {
    title: "Best Square Alternatives (2026)",
    href: "/payment-processing/alternatives/square",
    type: "Alternatives",
    category: "Payment Processing",
    entity: "Square",
    keywords: ["square alternatives", "square competitors"],
  },
  {
    title: "Best PayPal Business Alternatives (2026)",
    href: "/payment-processing/alternatives/paypal-business",
    type: "Alternatives",
    category: "Payment Processing",
    entity: "PayPal Business",
    keywords: ["paypal alternatives", "paypal business alternatives", "merchant account alternatives"],
  },
  {
    title: "Best Helcim Alternatives (2026)",
    href: "/payment-processing/alternatives/helcim",
    type: "Alternatives",
    category: "Payment Processing",
    entity: "Helcim",
    keywords: ["helcim alternatives", "interchange plus alternatives", "helcim competitors"],
  },
  {
    title: "Best Stax Alternatives (2026)",
    href: "/payment-processing/alternatives/stax",
    type: "Alternatives",
    category: "Payment Processing",
    entity: "Stax",
    keywords: ["stax alternatives", "fattmerchant alternatives", "membership payment processing alternatives"],
  },
  {
    title: "Best Shopify Payments Alternatives (2026)",
    href: "/payment-processing/alternatives/shopify-payments",
    type: "Alternatives",
    category: "Payment Processing",
    entity: "Shopify Payments",
    keywords: ["shopify payments alternatives", "shopify checkout alternatives"],
  },
  {
    title: "Best Authorize.net Alternatives (2026)",
    href: "/payment-processing/alternatives/authorize-net",
    type: "Alternatives",
    category: "Payment Processing",
    entity: "Authorize.net",
    keywords: ["authorize.net alternatives", "authorize net competitors", "payment gateway alternatives"],
  },
  {
    title: "Best Clover Alternatives (2026)",
    href: "/payment-processing/alternatives/clover",
    type: "Alternatives",
    category: "Payment Processing",
    entity: "Clover",
    keywords: ["clover alternatives", "clover pos alternatives", "fiserv clover competitors"],
  },

  // ——— Comparisons ———
  {
    title: "Gusto vs OnPay (2026)",
    href: "/payroll/compare/gusto-vs-onpay",
    type: "Comparison",
    category: "Payroll",
    keywords: ["gusto", "onpay", "gusto vs onpay", "payroll comparison"],
  },
  {
    title: "Gusto vs QuickBooks Payroll (2026)",
    href: "/payroll/compare/gusto-vs-quickbooks-payroll",
    type: "Comparison",
    category: "Payroll",
    keywords: ["gusto", "quickbooks payroll", "gusto vs quickbooks"],
  },
  {
    title: "HubSpot vs Salesforce (2026)",
    href: "/crm/compare/hubspot-vs-salesforce",
    type: "Comparison",
    category: "CRM",
    keywords: ["hubspot", "salesforce", "hubspot vs salesforce", "crm comparison"],
  },
  {
    title: "Zendesk vs Freshdesk (2026)",
    href: "/helpdesk/compare/zendesk-vs-freshdesk",
    type: "Comparison",
    category: "Helpdesk",
    keywords: ["zendesk", "freshdesk", "zendesk vs freshdesk", "helpdesk comparison"],
  },
  {
    title: "ServiceTitan vs Jobber (2026)",
    href: "/field-service/compare/servicetitan-vs-jobber",
    type: "Comparison",
    category: "Field Service",
    keywords: ["servicetitan", "jobber", "servicetitan vs jobber", "field service comparison"],
  },
  {
    title: "Simpro vs ServiceTitan (2026)",
    href: "/field-service/compare/simpro-vs-servicetitan",
    type: "Comparison",
    category: "Field Service",
    keywords: ["simpro", "servicetitan", "simpro vs servicetitan", "field service comparison"],
  },
  {
    title: "Zuper vs Jobber (2026)",
    href: "/field-service/compare/zuper-vs-jobber",
    type: "Comparison",
    category: "Field Service",
    keywords: ["zuper", "jobber", "zuper vs jobber", "field service comparison"],
  },
  {
    title: "Connecteam vs Jobber (2026)",
    href: "/field-service/compare/connecteam-vs-jobber",
    type: "Comparison",
    category: "Field Service",
    keywords: ["connecteam", "jobber", "connecteam vs jobber", "field service comparison"],
  },
  {
    title: "Square vs Shopify POS (2026)",
    href: "/pos/compare/square-pos-vs-shopify-pos",
    type: "Comparison",
    category: "POS",
    keywords: ["square pos", "shopify pos", "square vs shopify", "pos comparison"],
  },
  {
    title: "Thumbtack vs Angi (2026)",
    href: "/lead-generation/compare/thumbtack-vs-angi",
    type: "Comparison",
    category: "Lead Generation",
    keywords: ["thumbtack", "angi", "thumbtack vs angi", "lead generation comparison"],
  },
  {
    title: "Google LSA vs Yelp Ads (2026)",
    href: "/lead-generation/compare/google-local-services-ads-vs-yelp-ads",
    type: "Comparison",
    category: "Lead Generation",
    keywords: ["google lsa", "yelp ads", "local services ads vs yelp", "local lead ads"],
  },
  {
    title: "Google LSA vs Thumbtack (2026)",
    href: "/lead-generation/compare/google-local-services-ads-vs-thumbtack",
    type: "Comparison",
    category: "Lead Generation",
    keywords: ["google lsa vs thumbtack", "local services ads vs thumbtack", "thumbtack vs google", "lsa thumbtack"],
  },
  {
    title: "Thumbtack vs HomeAdvisor (2026)",
    href: "/lead-generation/compare/thumbtack-vs-homeadvisor",
    type: "Comparison",
    category: "Lead Generation",
    keywords: ["thumbtack vs homeadvisor", "homeadvisor vs thumbtack", "marketplace leads"],
  },
  {
    title: "Yelp Ads vs Thumbtack (2026)",
    href: "/lead-generation/compare/yelp-ads-vs-thumbtack",
    type: "Comparison",
    category: "Lead Generation",
    keywords: ["yelp vs thumbtack", "yelp ads vs thumbtack", "local leads"],
  },
  {
    title: "Google LSA vs Angi (2026)",
    href: "/lead-generation/compare/google-local-services-ads-vs-angi",
    type: "Comparison",
    category: "Lead Generation",
    keywords: ["google lsa vs angi", "local services ads angi", "angi vs google leads"],
  },
  {
    title: "Semrush vs Ahrefs (2026)",
    href: "/seo-tools/compare/semrush-vs-ahrefs",
    type: "Comparison",
    category: "SEO Tools",
    keywords: ["semrush vs ahrefs", "ahrefs vs semrush", "seo comparison"],
  },
  {
    title: "BrightLocal vs Whitespark (2026)",
    href: "/seo-tools/compare/brightlocal-vs-whitespark",
    type: "Comparison",
    category: "SEO Tools",
    keywords: ["brightlocal vs whitespark", "local seo comparison"],
  },
  {
    title: "CallRail vs CallTrackingMetrics (2026)",
    href: "/call-tracking/compare/callrail-vs-calltrackingmetrics",
    type: "Comparison",
    category: "Call Tracking",
    keywords: ["callrail vs calltrackingmetrics", "callrail vs ctm", "call tracking comparison"],
  },
  {
    title: "Podium vs Birdeye (2026)",
    href: "/reputation-management/compare/podium-vs-birdeye",
    type: "Comparison",
    category: "Reputation Management",
    keywords: ["podium vs birdeye", "review software comparison", "reputation management comparison"],
  },
  {
    title: "Mailchimp vs ActiveCampaign (2026)",
    href: "/email-marketing/compare/mailchimp-vs-activecampaign",
    type: "Comparison",
    category: "Email Marketing",
    keywords: ["mailchimp vs activecampaign", "email marketing comparison", "marketing automation"],
  },
  {
    title: "Klaviyo vs Mailchimp (2026)",
    href: "/email-marketing/compare/klaviyo-vs-mailchimp",
    type: "Comparison",
    category: "Email Marketing",
    keywords: ["klaviyo vs mailchimp", "klaviyo mailchimp comparison"],
  },
  {
    title: "Brevo vs Mailchimp (2026)",
    href: "/email-marketing/compare/brevo-vs-mailchimp",
    type: "Comparison",
    category: "Email Marketing",
    keywords: ["brevo vs mailchimp", "sendinblue vs mailchimp", "email sms software"],
  },
  {
    title: "Stripe vs Square (2026)",
    href: "/payment-processing/compare/stripe-vs-square",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["stripe vs square", "square vs stripe", "payment processor comparison"],
  },
  {
    title: "Stripe vs PayPal (2026)",
    href: "/payment-processing/compare/stripe-vs-paypal",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["stripe vs paypal", "paypal vs stripe"],
  },
  {
    title: "Square vs PayPal (2026)",
    href: "/payment-processing/compare/square-vs-paypal",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["square vs paypal", "paypal vs square"],
  },
  {
    title: "Helcim vs Stax (2026)",
    href: "/payment-processing/compare/helcim-vs-stax",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["helcim vs stax", "interchange plus processors"],
  },
  {
    title: "Shopify Payments vs Stripe (2026)",
    href: "/payment-processing/compare/shopify-payments-vs-stripe",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["shopify payments vs stripe", "shopify stripe comparison"],
  },
  {
    title: "Square vs Helcim (2026)",
    href: "/payment-processing/compare/square-vs-helcim",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["square vs helcim", "helcim vs square", "interchange plus vs square"],
  },
  {
    title: "Stripe vs Helcim (2026)",
    href: "/payment-processing/compare/stripe-vs-helcim",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["stripe vs helcim", "helcim vs stripe"],
  },
  {
    title: "Shopify Payments vs Square (2026)",
    href: "/payment-processing/compare/shopify-payments-vs-square",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["shopify payments vs square", "square vs shopify payments"],
  },
  {
    title: "Square vs Clover (2026)",
    href: "/payment-processing/compare/square-vs-clover",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["square vs clover", "clover vs square"],
  },
  {
    title: "Stripe vs Clover (2026)",
    href: "/payment-processing/compare/stripe-vs-clover",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["stripe vs clover", "clover vs stripe"],
  },
  {
    title: "Shopify Payments vs PayPal (2026)",
    href: "/payment-processing/compare/shopify-payments-vs-paypal",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["shopify payments vs paypal", "paypal vs shopify payments"],
  },
  {
    title: "Helcim vs PayPal (2026)",
    href: "/payment-processing/compare/helcim-vs-paypal",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["helcim vs paypal", "paypal vs helcim"],
  },
  {
    title: "Stripe vs Stax (2026)",
    href: "/payment-processing/compare/stripe-vs-stax",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["stripe vs stax", "stax vs stripe"],
  },
  {
    title: "Square vs Stax (2026)",
    href: "/payment-processing/compare/square-vs-stax",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["square vs stax", "stax vs square"],
  },
  {
    title: "Stax vs PayPal (2026)",
    href: "/payment-processing/compare/stax-vs-paypal",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["stax vs paypal", "paypal vs stax"],
  },
  {
    title: "Authorize.net vs Stripe (2026)",
    href: "/payment-processing/compare/authorize-net-vs-stripe",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["authorize.net vs stripe", "stripe vs authorize.net", "authorize net stripe"],
  },
  {
    title: "Authorize.net vs Square (2026)",
    href: "/payment-processing/compare/authorize-net-vs-square",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["authorize.net vs square", "square vs authorize.net"],
  },
  {
    title: "Authorize.net vs PayPal (2026)",
    href: "/payment-processing/compare/authorize-net-vs-paypal",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["authorize.net vs paypal", "paypal vs authorize.net"],
  },
  {
    title: "Authorize.net vs Shopify Payments (2026)",
    href: "/payment-processing/compare/authorize-net-vs-shopify-payments",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["authorize.net vs shopify", "shopify payments vs authorize.net"],
  },
  {
    title: "Authorize.net vs Helcim (2026)",
    href: "/payment-processing/compare/authorize-net-vs-helcim",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["authorize.net vs helcim", "helcim vs authorize.net"],
  },
  {
    title: "Authorize.net vs Stax (2026)",
    href: "/payment-processing/compare/authorize-net-vs-stax",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["authorize.net vs stax", "stax vs authorize.net"],
  },
  {
    title: "Authorize.net vs Clover (2026)",
    href: "/payment-processing/compare/authorize-net-vs-clover",
    type: "Comparison",
    category: "Payment Processing",
    keywords: ["authorize.net vs clover", "clover vs authorize.net"],
  },
  {
    title: "CallRail vs WhatConverts (2026)",
    href: "/call-tracking/compare/callrail-vs-whatconverts",
    type: "Comparison",
    category: "Call Tracking",
    keywords: ["callrail vs whatconverts", "whatconverts vs callrail"],
  },

  // ——— Best software roundups ———
  {
    title: "Best Payroll Software (2026)",
    href: "/payroll/best-payroll-software",
    type: "Best Software",
    category: "Payroll",
    keywords: ["payroll software", "best payroll", "best payroll software"],
  },
  {
    title: "Best Accounting Software (2026)",
    href: "/accounting/best-accounting-software",
    type: "Best Software",
    category: "Accounting",
    keywords: ["accounting software", "best accounting", "best accounting software"],
  },
  {
    title: "Best Accounting Software for HVAC Businesses (2026)",
    href: "/accounting/best-for/hvac",
    type: "Best For",
    category: "Accounting",
    keywords: ["hvac accounting software", "contractor accounting", "hvac bookkeeping"],
  },
  {
    title: "Best Accounting Software for Plumbing Companies (2026)",
    href: "/accounting/best-for/plumbing",
    type: "Best For",
    category: "Accounting",
    keywords: ["plumbing accounting software", "plumber bookkeeping"],
  },
  {
    title: "Best Accounting Software for Electricians (2026)",
    href: "/accounting/best-for/electricians",
    type: "Best For",
    category: "Accounting",
    keywords: ["electrician accounting software", "electrical contractor bookkeeping"],
  },
  {
    title: "Best Accounting Software for Painting Contractors (2026)",
    href: "/accounting/best-for/painting",
    type: "Best For",
    category: "Accounting",
    keywords: ["painting contractor accounting", "painter bookkeeping"],
  },
  {
    title: "Best Accounting Software for Roofing Companies (2026)",
    href: "/accounting/best-for/roofing",
    type: "Best For",
    category: "Accounting",
    keywords: ["roofing accounting software", "roofing company books"],
  },
  {
    title: "Best Accounting Software for General Contractors (2026)",
    href: "/accounting/best-for/general-contractors",
    type: "Best For",
    category: "Accounting",
    keywords: ["gc accounting software", "general contractor bookkeeping"],
  },
  {
    title: "Best Accounting Software for Landscaping Companies (2026)",
    href: "/accounting/best-for/landscaping",
    type: "Best For",
    category: "Accounting",
    keywords: ["landscaping accounting software", "lawn care bookkeeping"],
  },
  {
    title: "Best Accounting Software for Construction Companies (2026)",
    href: "/accounting/best-for/construction",
    type: "Best For",
    category: "Accounting",
    keywords: ["construction accounting software", "construction bookkeeping"],
  },
  {
    title: "Best Accounting Software for Remodeling Businesses (2026)",
    href: "/accounting/best-for/remodeling",
    type: "Best For",
    category: "Accounting",
    keywords: ["remodeling accounting software", "renovation bookkeeping"],
  },
  {
    title: "Best Accounting Software for Handyman Businesses (2026)",
    href: "/accounting/best-for/handyman",
    type: "Best For",
    category: "Accounting",
    keywords: ["handyman accounting software", "handyman bookkeeping"],
  },
  {
    title: "Best Accounting Software for Property Management Companies (2026)",
    href: "/accounting/best-for/property-management",
    type: "Best For",
    category: "Accounting",
    keywords: ["property management accounting", "pm company bookkeeping"],
  },
  {
    title: "Best Accounting Software for Pest Control Businesses (2026)",
    href: "/accounting/best-for/pest-control",
    type: "Best For",
    category: "Accounting",
    keywords: ["pest control accounting software", "exterminator bookkeeping"],
  },
  {
    title: "Best Accounting Software for Pool Service Companies (2026)",
    href: "/accounting/best-for/pool-service",
    type: "Best For",
    category: "Accounting",
    keywords: ["pool service accounting", "pool company bookkeeping"],
  },
  {
    title: "Best Accounting Software for Junk Removal Businesses (2026)",
    href: "/accounting/best-for/junk-removal",
    type: "Best For",
    category: "Accounting",
    keywords: ["junk removal accounting", "hauling bookkeeping"],
  },
  {
    title: "Best Accounting Software for Moving Companies (2026)",
    href: "/accounting/best-for/moving",
    type: "Best For",
    category: "Accounting",
    keywords: ["moving company accounting", "movers bookkeeping"],
  },
  {
    title: "Best CRM Software (2026)",
    href: "/crm/best-crm-software",
    type: "Best Software",
    category: "CRM",
    keywords: ["crm software", "best crm", "best crm software"],
  },
  {
    title: "Best Helpdesk Software (2026)",
    href: "/helpdesk/best-helpdesk-software",
    type: "Best Software",
    category: "Helpdesk",
    keywords: ["helpdesk software", "best helpdesk", "best helpdesk software"],
  },
  {
    title: "Best Field Service Software (2026)",
    href: "/field-service/best-field-service-software",
    type: "Best Software",
    category: "Field Service",
    keywords: ["field service software", "best field service"],
  },
  {
    title: "Best POS Software (2026)",
    href: "/pos/best-pos-software",
    type: "Best Software",
    category: "POS",
    keywords: ["pos software", "best pos", "best pos software"],
  },
  {
    title: "Best Inventory Software (2026)",
    href: "/inventory/best-inventory-software",
    type: "Best Software",
    category: "Inventory",
    keywords: ["inventory software", "best inventory", "best inventory software"],
  },
  {
    title: "Best HR Software (2026)",
    href: "/hr/best-hr-software",
    type: "Best Software",
    category: "HR",
    keywords: ["hr software", "best hr", "best hr software"],
  },
  {
    title: "Best Scheduling Software (2026)",
    href: "/scheduling/best-scheduling-software",
    type: "Best Software",
    category: "Scheduling",
    keywords: ["scheduling software", "best scheduling", "best scheduling software"],
  },
  {
    title: "Best Time Tracking Software (2026)",
    href: "/time-tracking/best-time-tracking-software",
    type: "Best Software",
    category: "Time Tracking",
    keywords: ["time tracking software", "best time tracking"],
  },
  {
    title: "Best Website Builders (2026)",
    href: "/website-builders/best-website-builders",
    type: "Best Software",
    category: "Website Builders",
    keywords: ["best website builders", "contractor website builder", "small business website builder"],
  },
  {
    title: "Best Lead Generation Tools (2026)",
    href: "/lead-generation/best-lead-generation-tools",
    type: "Best Software",
    category: "Lead Generation",
    keywords: ["best lead generation tools", "contractor leads", "local service leads"],
  },
  {
    title: "Best SEO Tools (2026)",
    href: "/seo-tools/best-seo-tools",
    type: "Best Software",
    category: "SEO Tools",
    keywords: ["best seo tools", "local seo software", "contractor seo tools"],
  },
  {
    title: "Best Call Tracking Software (2026)",
    href: "/call-tracking/best-call-tracking-software",
    type: "Best Software",
    category: "Call Tracking",
    keywords: ["best call tracking software", "callrail", "marketing call attribution"],
  },
  {
    title: "Best Reputation Management Software (2026)",
    href: "/reputation-management/best-reputation-management-software",
    type: "Best Software",
    category: "Reputation Management",
    keywords: ["best reputation management software", "best review software", "contractor review management"],
  },
  {
    title: "Best Email Marketing Software (2026)",
    href: "/email-marketing/best-email-marketing-software",
    type: "Best Software",
    category: "Email Marketing",
    keywords: ["best email marketing software", "email marketing for contractors", "mailchimp alternatives"],
  },
  {
    title: "Best Payment Processing Software (2026)",
    href: "/payment-processing/best-payment-processing-software",
    type: "Best Software",
    category: "Payment Processing",
    keywords: ["best payment processing software", "best merchant services", "stripe square comparison"],
  },

  // ——— Best-for pages (selected high-intent) ———
  {
    title: "Best Payroll Software for Small Business",
    href: "/payroll/best-for/small-business",
    type: "Best For",
    category: "Payroll",
    keywords: ["payroll", "small business", "best payroll for small business"],
  },
  {
    title: "Best Payroll Software for Contractors",
    href: "/payroll/best-for/contractors",
    type: "Best For",
    category: "Payroll",
    keywords: ["payroll", "contractors", "best payroll for contractors"],
  },
  {
    title: "Best Payroll Software for Junk Removal Businesses (2026)",
    href: "/payroll/best-for/junk-removal",
    type: "Best For",
    category: "Payroll",
    keywords: ["junk removal payroll", "hauling payroll", "w2 1099 payroll small crew"],
  },
  {
    title: "Best Payroll Software for Moving Companies (2026)",
    href: "/payroll/best-for/moving",
    type: "Best For",
    category: "Payroll",
    keywords: ["moving company payroll", "movers payroll", "seasonal crew payroll"],
  },
  {
    title: "Best Field Service Software for HVAC Businesses",
    href: "/field-service/best-for/hvac",
    type: "Best For",
    category: "Field Service",
    keywords: ["field service", "hvac", "hvac software", "fsm for hvac"],
  },
  {
    title: "Best Field Service Software for Plumbing Companies",
    href: "/field-service/best-for/plumbing",
    type: "Best For",
    category: "Field Service",
    keywords: ["field service", "plumbing", "plumbing software", "fsm for plumbers"],
  },
  {
    title: "Best Field Service Software for Landscaping Companies",
    href: "/field-service/best-for/landscaping",
    type: "Best For",
    category: "Field Service",
    keywords: ["landscaping software", "field service", "lawn care software"],
  },
  {
    title: "Best Field Service Software for Roofing Companies",
    href: "/field-service/best-for/roofing",
    type: "Best For",
    category: "Field Service",
    keywords: ["roofing software", "field service", "fsm roofing"],
  },
  {
    title: "Best Field Service Software for Pool Service Companies",
    href: "/field-service/best-for/pool-service",
    type: "Best For",
    category: "Field Service",
    keywords: ["pool service software", "field service", "pool business software"],
  },
  {
    title: "Best Project Management Software for HVAC Businesses",
    href: "/project-management/best-for/hvac",
    type: "Best For",
    category: "Project Management",
    keywords: ["project management", "hvac", "contractor pm software", "job project tracking"],
  },
  {
    title: "Best Project Management Software for Construction Companies",
    href: "/project-management/best-for/construction",
    type: "Best For",
    category: "Project Management",
    keywords: ["construction project management software", "contractor pm", "small construction team tools"],
  },
  {
    title: "Best Project Management Software for General Contractors",
    href: "/project-management/best-for/general-contractors",
    type: "Best For",
    category: "Project Management",
    keywords: ["general contractor software", "project management", "gc job tracking"],
  },
  {
    title: "Best Project Management Software for Property Management Companies",
    href: "/project-management/best-for/property-management",
    type: "Best For",
    category: "Project Management",
    keywords: ["property management software", "project management", "turnover projects pm"],
  },
  {
    title: "Best POS for Small Business",
    href: "/pos/best-for/small-business",
    type: "Best For",
    category: "POS",
    keywords: ["pos", "small business", "best pos for small business"],
  },
  {
    title: "Best POS Software for HVAC Businesses (2026)",
    href: "/pos/best-for/hvac",
    type: "Best For",
    category: "POS",
    keywords: ["hvac pos", "pos for hvac", "contractor pos"],
  },
  {
    title: "Best POS Software for Plumbing Companies (2026)",
    href: "/pos/best-for/plumbing",
    type: "Best For",
    category: "POS",
    keywords: ["plumbing pos", "plumber pos software"],
  },
  {
    title: "Best POS Software for Electricians (2026)",
    href: "/pos/best-for/electricians",
    type: "Best For",
    category: "POS",
    keywords: ["electrician pos", "electrical contractor pos"],
  },
  {
    title: "Best POS Software for Painting Contractors (2026)",
    href: "/pos/best-for/painting",
    type: "Best For",
    category: "POS",
    keywords: ["painting contractor pos", "pos for painters"],
  },
  {
    title: "Best POS Software for Roofing Companies (2026)",
    href: "/pos/best-for/roofing",
    type: "Best For",
    category: "POS",
    keywords: ["roofing pos", "roofing company pos"],
  },
  {
    title: "Best POS Software for General Contractors (2026)",
    href: "/pos/best-for/general-contractors",
    type: "Best For",
    category: "POS",
    keywords: ["general contractor pos", "gc pos software"],
  },
  {
    title: "Best POS Software for Landscaping Companies (2026)",
    href: "/pos/best-for/landscaping",
    type: "Best For",
    category: "POS",
    keywords: ["landscaping pos", "lawn care pos"],
  },
  {
    title: "Best POS Software for Construction Companies (2026)",
    href: "/pos/best-for/construction",
    type: "Best For",
    category: "POS",
    keywords: ["construction pos", "construction company pos"],
  },
  {
    title: "Best POS Software for Remodeling Businesses (2026)",
    href: "/pos/best-for/remodeling",
    type: "Best For",
    category: "POS",
    keywords: ["remodeling pos", "renovation pos"],
  },
  {
    title: "Best POS Software for Handyman Businesses (2026)",
    href: "/pos/best-for/handyman",
    type: "Best For",
    category: "POS",
    keywords: ["handyman pos", "handyman business pos"],
  },
  {
    title: "Best POS Software for Property Management Companies (2026)",
    href: "/pos/best-for/property-management",
    type: "Best For",
    category: "POS",
    keywords: ["property management pos", "pm company pos"],
  },
  {
    title: "Best POS Software for Pest Control Businesses (2026)",
    href: "/pos/best-for/pest-control",
    type: "Best For",
    category: "POS",
    keywords: ["pest control pos", "exterminator pos"],
  },
  {
    title: "Best POS Software for Pool Service Companies (2026)",
    href: "/pos/best-for/pool-service",
    type: "Best For",
    category: "POS",
    keywords: ["pool service pos", "pool company pos"],
  },
  {
    title: "Best POS Software for Junk Removal Businesses (2026)",
    href: "/pos/best-for/junk-removal",
    type: "Best For",
    category: "POS",
    keywords: ["junk removal pos", "hauling pos"],
  },
  {
    title: "Best POS Software for Moving Companies (2026)",
    href: "/pos/best-for/moving",
    type: "Best For",
    category: "POS",
    keywords: ["moving company pos", "movers pos"],
  },
  {
    title: "Best Inventory Software for Small Business",
    href: "/inventory/best-for/small-business",
    type: "Best For",
    category: "Inventory",
    keywords: ["inventory", "small business", "inventory software for small business"],
  },
  {
    title: "Best Inventory Management Software for HVAC Businesses",
    href: "/inventory/best-for/hvac",
    type: "Best For",
    category: "Inventory",
    keywords: ["hvac inventory software", "inventory", "truck stock"],
  },
  {
    title: "Best Inventory Management Software for Plumbing Companies",
    href: "/inventory/best-for/plumbing",
    type: "Best For",
    category: "Inventory",
    keywords: ["plumbing inventory", "parts inventory", "contractor inventory"],
  },
  {
    title: "Best Inventory Management Software for Electricians",
    href: "/inventory/best-for/electricians",
    type: "Best For",
    category: "Inventory",
    keywords: ["electrician inventory", "van stock", "electrical contractor inventory"],
  },
  {
    title: "Best Inventory Management Software for Painting Contractors",
    href: "/inventory/best-for/painting",
    type: "Best For",
    category: "Inventory",
    keywords: ["painting contractor inventory", "paint inventory software"],
  },
  {
    title: "Best Inventory Management Software for Roofing Companies",
    href: "/inventory/best-for/roofing",
    type: "Best For",
    category: "Inventory",
    keywords: ["roofing inventory", "contractor materials inventory"],
  },
  {
    title: "Best Inventory Management Software for General Contractors",
    href: "/inventory/best-for/general-contractors",
    type: "Best For",
    category: "Inventory",
    keywords: ["gc inventory", "construction inventory software", "job materials"],
  },
  {
    title: "Best Inventory Management Software for Landscaping Companies",
    href: "/inventory/best-for/landscaping",
    type: "Best For",
    category: "Inventory",
    keywords: ["landscaping inventory", "bulk material inventory"],
  },
  {
    title: "Best Inventory Management Software for Construction Companies",
    href: "/inventory/best-for/construction",
    type: "Best For",
    category: "Inventory",
    keywords: ["construction inventory management", "job site inventory"],
  },
  {
    title: "Best Inventory Management Software for Remodeling Businesses",
    href: "/inventory/best-for/remodeling",
    type: "Best For",
    category: "Inventory",
    keywords: ["remodeling inventory", "finish materials inventory"],
  },
  {
    title: "Best Inventory Management Software for Handyman Businesses",
    href: "/inventory/best-for/handyman",
    type: "Best For",
    category: "Inventory",
    keywords: ["handyman inventory", "small contractor inventory"],
  },
  {
    title: "Best Inventory Management Software for Property Management Companies",
    href: "/inventory/best-for/property-management",
    type: "Best For",
    category: "Inventory",
    keywords: ["property management inventory", "mro inventory"],
  },
  {
    title: "Best Inventory Management Software for Pest Control Businesses",
    href: "/inventory/best-for/pest-control",
    type: "Best For",
    category: "Inventory",
    keywords: ["pest control inventory", "route truck stock"],
  },
  {
    title: "Best Inventory Management Software for Pool Service Companies",
    href: "/inventory/best-for/pool-service",
    type: "Best For",
    category: "Inventory",
    keywords: ["pool service inventory", "chemical inventory"],
  },
  {
    title: "Best Inventory Management Software for Junk Removal Businesses",
    href: "/inventory/best-for/junk-removal",
    type: "Best For",
    category: "Inventory",
    keywords: ["junk removal inventory", "supplies inventory"],
  },
  {
    title: "Best Inventory Management Software for Moving Companies",
    href: "/inventory/best-for/moving",
    type: "Best For",
    category: "Inventory",
    keywords: ["moving company inventory", "boxes packing supplies inventory"],
  },
  {
    title: "Best Website Builders for Contractors",
    href: "/website-builders/best-for/contractors",
    type: "Best For",
    category: "Website Builders",
    keywords: ["website builder", "contractors", "best website builder for contractors"],
  },
  {
    title: "Best Reputation Management for Contractors",
    href: "/reputation-management/best-for/contractors",
    type: "Best For",
    category: "Reputation Management",
    keywords: ["best reputation management for contractors", "contractor review software"],
  },
  {
    title: "Best Email Marketing for Contractors",
    href: "/email-marketing/best-for/contractors",
    type: "Best For",
    category: "Email Marketing",
    keywords: ["best email marketing for contractors", "contractor email software"],
  },
  {
    title: "Best Email Marketing for Small Business",
    href: "/email-marketing/best-for/small-business",
    type: "Best For",
    category: "Email Marketing",
    keywords: ["best email marketing small business", "service business email marketing"],
  },
  {
    title: "Best Payment Processing for Contractors",
    href: "/payment-processing/best-for/contractors",
    type: "Best For",
    category: "Payment Processing",
    keywords: ["payment processing contractors", "contractor credit card processing"],
  },
  {
    title: "Best Payment Processing for Small Business",
    href: "/payment-processing/best-for/small-business",
    type: "Best For",
    category: "Payment Processing",
    keywords: ["small business payment processing", "best payment processor small business"],
  },

  // ——— Guides (major) ———
  {
    title: "How Payroll Software Works",
    href: "/payroll/guides/how-payroll-software-works",
    type: "Guide",
    category: "Payroll",
    keywords: ["how payroll software works", "payroll guide"],
  },
  {
    title: "How to Choose Field Service Software",
    href: "/field-service/guides/how-to-choose-field-service-software",
    type: "Guide",
    category: "Field Service",
    keywords: ["how to choose field service software", "field service guide"],
  },
  {
    title: "Best HR Software for Small Business",
    href: "/hr/guides/best-hr-software-for-small-business",
    type: "Guide",
    category: "HR",
    keywords: ["hr software", "best hr software for small business"],
  },
  {
    title: "Project Management for Small Business",
    href: "/project-management/guides/project-management-for-small-business",
    type: "Guide",
    category: "Project Management",
    keywords: ["project management", "small business", "project management guide"],
  },
  {
    title: "Helpdesk Software for Startups",
    href: "/helpdesk/guides/helpdesk-software-for-startups",
    type: "Guide",
    category: "Helpdesk",
    keywords: ["helpdesk", "startups", "helpdesk software for startups"],
  },
  {
    title: "Inventory Software for Ecommerce",
    href: "/inventory/guides/inventory-software-for-ecommerce",
    type: "Guide",
    category: "Inventory",
    keywords: ["inventory", "ecommerce", "inventory software for ecommerce"],
  },
  {
    title: "How to Choose a Website Builder",
    href: "/website-builders/guides/how-to-choose-a-website-builder",
    type: "Guide",
    category: "Website Builders",
    keywords: ["how to choose a website builder", "website builder guide", "service business website"],
  },
  {
    title: "How to Get Leads for Contractors",
    href: "/lead-generation/guides/how-to-get-leads-for-contractors",
    type: "Guide",
    category: "Lead Generation",
    keywords: ["contractor leads", "how to get leads", "trade lead generation"],
  },
  {
    title: "How to Choose a Lead Generation Platform",
    href: "/lead-generation/guides/how-to-choose-a-lead-generation-platform",
    type: "Guide",
    category: "Lead Generation",
    keywords: ["lead generation platform", "choose lead gen software", "local leads guide"],
  },
  {
    title: "Hostinger vs Wix",
    href: "/website-builders/compare/hostinger-website-builder-vs-wix",
    type: "Comparison",
    category: "Website Builders",
    keywords: ["hostinger website builder", "wix", "hostinger vs wix"],
  },
  {
    title: "GoDaddy vs Hostinger",
    href: "/website-builders/compare/godaddy-website-builder-vs-hostinger-website-builder",
    type: "Comparison",
    category: "Website Builders",
    keywords: ["godaddy website builder", "hostinger", "godaddy vs hostinger"],
  },
  {
    title: "Best SEO Tools for Contractors",
    href: "/seo-tools/best-for/contractors",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["seo tools contractors", "contractor seo", "local seo contractors"],
  },
  {
    title: "Best SEO Tools for Local SEO",
    href: "/seo-tools/best-for/local-seo",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["best local seo tools", "map pack seo software"],
  },
  {
    title: "Best SEO Tools by Use Case",
    href: "/seo-tools/best-for",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["best seo tools by trade", "seo tools scenarios", "local business seo tools"],
  },
  {
    title: "Best SEO Tools for HVAC Businesses (2026)",
    href: "/seo-tools/best-for/hvac",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["hvac seo tools", "local seo hvac"],
  },
  {
    title: "Best SEO Tools for Plumbing Companies (2026)",
    href: "/seo-tools/best-for/plumbing",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["plumbing seo tools", "plumber local seo"],
  },
  {
    title: "Best SEO Tools for Electricians (2026)",
    href: "/seo-tools/best-for/electricians",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["electrician seo tools", "electrical contractor seo"],
  },
  {
    title: "Best SEO Tools for Painting Contractors (2026)",
    href: "/seo-tools/best-for/painting",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["painting contractor seo", "house painter seo tools"],
  },
  {
    title: "Best SEO Tools for Roofing Companies (2026)",
    href: "/seo-tools/best-for/roofing",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["roofing seo tools", "roofer local seo"],
  },
  {
    title: "Best SEO Tools for General Contractors (2026)",
    href: "/seo-tools/best-for/general-contractors",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["general contractor seo tools", "gc seo software"],
  },
  {
    title: "Best SEO Tools for Landscaping Companies (2026)",
    href: "/seo-tools/best-for/landscaping",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["landscaping seo tools", "lawn care local seo"],
  },
  {
    title: "Best SEO Tools for Construction Companies (2026)",
    href: "/seo-tools/best-for/construction",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["construction company seo tools", "builder seo software"],
  },
  {
    title: "Best SEO Tools for Remodeling Businesses (2026)",
    href: "/seo-tools/best-for/remodeling",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["remodeling seo tools", "kitchen remodel seo"],
  },
  {
    title: "Best SEO Tools for Handyman Businesses (2026)",
    href: "/seo-tools/best-for/handyman",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["handyman seo tools", "handyman local seo"],
  },
  {
    title: "Best SEO Tools for Property Management Companies (2026)",
    href: "/seo-tools/best-for/property-management",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["property management seo tools", "pm company local seo"],
  },
  {
    title: "Best SEO Tools for Pest Control Businesses (2026)",
    href: "/seo-tools/best-for/pest-control",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["pest control seo tools", "exterminator local seo"],
  },
  {
    title: "Best SEO Tools for Pool Service Companies (2026)",
    href: "/seo-tools/best-for/pool-service",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["pool service seo tools", "pool company local seo"],
  },
  {
    title: "Best SEO Tools for Junk Removal Businesses (2026)",
    href: "/seo-tools/best-for/junk-removal",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["junk removal seo tools", "hauling local seo"],
  },
  {
    title: "Best SEO Tools for Moving Companies (2026)",
    href: "/seo-tools/best-for/moving",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["moving company seo tools", "movers local seo"],
  },
  {
    title: "How to Do SEO for Contractors",
    href: "/seo-tools/guides/how-to-do-seo-for-contractors",
    type: "Guide",
    category: "SEO Tools",
    keywords: ["contractor seo guide", "local seo contractors", "trade seo"],
  },
  {
    title: "How to Rank in Google Maps",
    href: "/seo-tools/guides/how-to-rank-in-google-maps",
    type: "Guide",
    category: "SEO Tools",
    keywords: ["google maps ranking", "map pack seo", "local pack"],
  },
  {
    title: "Best Call Tracking for Contractors",
    href: "/call-tracking/best-for/contractors",
    type: "Best For",
    category: "Call Tracking",
    keywords: ["call tracking contractors", "contractor call attribution", "lsa call tracking"],
  },
  {
    title: "What Is Call Tracking?",
    href: "/call-tracking/guides/what-is-call-tracking",
    type: "Guide",
    category: "Call Tracking",
    keywords: ["what is call tracking", "dynamic number insertion", "dni"],
  },
  {
    title: "How Call Tracking Works",
    href: "/call-tracking/guides/how-call-tracking-works",
    type: "Guide",
    category: "Call Tracking",
    keywords: ["how call tracking works", "call tracking setup"],
  },
  {
    title: "How to Get More Google Reviews",
    href: "/reputation-management/guides/how-to-get-more-google-reviews",
    type: "Guide",
    category: "Reputation Management",
    keywords: ["how to get more google reviews", "google review strategy", "local service reviews"],
  },
  {
    title: "How to Use Email Marketing for Contractors",
    href: "/email-marketing/guides/how-to-use-email-marketing-for-contractors",
    type: "Guide",
    category: "Email Marketing",
    keywords: ["contractor email marketing", "email marketing for trades", "service business email"],
  },
  {
    title: "Email Marketing for Local Business",
    href: "/email-marketing/guides/email-marketing-for-local-business",
    type: "Guide",
    category: "Email Marketing",
    keywords: ["local business email marketing", "small business newsletter"],
  },
  {
    title: "Email Marketing vs SMS Marketing",
    href: "/email-marketing/guides/email-marketing-vs-sms-marketing",
    type: "Guide",
    category: "Email Marketing",
    keywords: ["email vs sms marketing", "sms marketing contractors"],
  },
  {
    title: "How to Build an Email List",
    href: "/email-marketing/guides/how-to-build-an-email-list",
    type: "Guide",
    category: "Email Marketing",
    keywords: ["how to build an email list", "email list for contractors"],
  },
  {
    title: "Best Email Campaigns for Service Businesses",
    href: "/email-marketing/guides/best-email-campaigns-for-service-businesses",
    type: "Guide",
    category: "Email Marketing",
    keywords: ["email campaigns service business", "contractor email campaigns"],
  },
  {
    title: "How Payment Processing Works",
    href: "/payment-processing/guides/how-payment-processing-works",
    type: "Guide",
    category: "Payment Processing",
    keywords: ["how payment processing works", "merchant account explained"],
  },
  {
    title: "Payment Processing for Contractors",
    href: "/payment-processing/guides/payment-processing-for-contractors",
    type: "Guide",
    category: "Payment Processing",
    keywords: ["contractor payment processing", "trades credit card processing"],
  },
  {
    title: "Credit Card Processing Fees Explained",
    href: "/payment-processing/guides/credit-card-processing-fees-explained",
    type: "Guide",
    category: "Payment Processing",
    keywords: ["credit card processing fees", "interchange fees explained"],
  },
  {
    title: "Stripe vs Square Fees",
    href: "/payment-processing/guides/stripe-vs-square-fees",
    type: "Guide",
    category: "Payment Processing",
    keywords: ["stripe vs square fees", "square stripe pricing"],
  },
  {
    title: "How to Choose a Payment Processor",
    href: "/payment-processing/guides/how-to-choose-a-payment-processor",
    type: "Guide",
    category: "Payment Processing",
    keywords: ["how to choose payment processor", "pick a merchant account"],
  },
];

