export type SearchItemType =
  | "Review"
  | "Comparison"
  | "Alternatives"
  | "Guide"
  | "Best Software"
  | "Best For"
  | "Category";

export type SearchIndexItem = {
  title: string;
  href: string;
  type: SearchItemType;
  category: string;
  entity?: string;
  keywords: string[];
};

/**
  * Local search index for BeltStack.
  *
  * This is intentionally small and focused on primary entities/topics:
  * - key reviews
  * - high-intent comparisons
  * - alternatives pages
  * - best-software roundups
  * - major best-for pages
  * - major guides
  * - category hubs
  *
  * In the future this can be generated automatically from hub data files.
  */
export const searchIndex: SearchIndexItem[] = [
  // ——— Category hubs ———
  {
    title: "Payroll Software",
    href: "/payroll",
    type: "Category",
    category: "Payroll",
    keywords: ["payroll", "payroll software", "contractor payroll", "trade payroll"],
  },
  {
    title: "Accounting Software",
    href: "/accounting",
    type: "Category",
    category: "Accounting",
    keywords: ["accounting", "bookkeeping", "contractor accounting"],
  },
  {
    title: "CRM Software",
    href: "/crm",
    type: "Category",
    category: "CRM",
    keywords: ["crm", "crm software", "customer management"],
  },
  {
    title: "Field Service Software",
    href: "/field-service",
    type: "Category",
    category: "Field Service",
    keywords: ["field service", "fsm", "hvac software", "plumbing software"],
  },
  {
    title: "Project Management Software",
    href: "/project-management",
    type: "Category",
    category: "Project Management",
    keywords: ["project management", "job management", "projects"],
  },
  {
    title: "Helpdesk Software",
    href: "/helpdesk",
    type: "Category",
    category: "Helpdesk",
    keywords: ["helpdesk", "support software", "ticketing"],
  },
  {
    title: "POS Software",
    href: "/pos",
    type: "Category",
    category: "POS",
    keywords: ["pos", "point of sale", "retail pos"],
  },
  {
    title: "Inventory Software",
    href: "/inventory",
    type: "Category",
    category: "Inventory",
    keywords: ["inventory", "inventory management", "stock tracking"],
  },
  {
    title: "Scheduling Software",
    href: "/scheduling",
    type: "Category",
    category: "Scheduling",
    keywords: ["scheduling", "appointment scheduling", "booking"],
  },
  {
    title: "Time Tracking Software",
    href: "/time-tracking",
    type: "Category",
    category: "Time Tracking",
    keywords: ["time tracking", "timesheets", "billable hours"],
  },
  {
    title: "HR Software",
    href: "/hr",
    type: "Category",
    category: "HR",
    keywords: ["hr", "hr software", "people ops"],
  },
  {
    title: "Invoicing Software",
    href: "/invoicing",
    type: "Category",
    category: "Invoicing",
    keywords: ["invoicing", "invoice software", "billing"],
  },
  {
    title: "Website Builders",
    href: "/website-builders",
    type: "Category",
    category: "Website Builders",
    keywords: ["website builders", "website builder", "small business website", "contractor website"],
  },
  {
    title: "Lead Generation Tools",
    href: "/lead-generation",
    type: "Category",
    category: "Lead Generation",
    keywords: ["lead generation", "local leads", "contractor leads", "home services leads", "thumbtack", "angi"],
  },
  {
    title: "SEO Tools",
    href: "/seo-tools",
    type: "Category",
    category: "SEO Tools",
    keywords: ["seo tools", "local seo", "semrush", "ahrefs", "google maps seo", "contractor seo"],
  },
  {
    title: "Call Tracking Software",
    href: "/call-tracking",
    type: "Category",
    category: "Call Tracking",
    keywords: ["call tracking", "callrail", "dynamic number insertion", "marketing attribution", "phone call tracking"],
  },

  // ——— Reviews (popular entities) ———
  {
    title: "Gusto Review (2026)",
    href: "/payroll/review/gusto",
    type: "Review",
    category: "Payroll",
    entity: "Gusto",
    keywords: ["gusto", "gusto review", "gusto payroll"],
  },
  {
    title: "QuickBooks Online Review (2026)",
    href: "/accounting/review/quickbooks-online",
    type: "Review",
    category: "Accounting",
    entity: "QuickBooks Online",
    keywords: ["quickbooks", "quickbooks online", "quickbooks accounting"],
  },
  {
    title: "HubSpot CRM Review (2026)",
    href: "/crm/review/hubspot",
    type: "Review",
    category: "CRM",
    entity: "HubSpot",
    keywords: ["hubspot", "hubspot crm", "hubspot review"],
  },
  {
    title: "Zendesk Review (2026)",
    href: "/helpdesk/review/zendesk",
    type: "Review",
    category: "Helpdesk",
    entity: "Zendesk",
    keywords: ["zendesk", "zendesk review", "zendesk helpdesk"],
  },
  {
    title: "ServiceTitan Review (2026)",
    href: "/field-service/review/servicetitan",
    type: "Review",
    category: "Field Service",
    entity: "ServiceTitan",
    keywords: ["servicetitan", "servicetitan review", "field service software"],
  },
  {
    title: "Connecteam Review (2026)",
    href: "/field-service/review/connecteam",
    type: "Review",
    category: "Field Service",
    entity: "Connecteam",
    keywords: ["connecteam", "connecteam review", "deskless workforce", "field service software"],
  },
  {
    title: "Oracle Field Service Review (2026)",
    href: "/field-service/review/oracle-field-service",
    type: "Review",
    category: "Field Service",
    entity: "Oracle Field Service",
    keywords: ["oracle field service", "oracle field service review", "enterprise field service"],
  },
  {
    title: "Simpro Review (2026)",
    href: "/field-service/review/simpro",
    type: "Review",
    category: "Field Service",
    entity: "Simpro",
    keywords: ["simpro", "simpro review", "trade field service software"],
  },
  {
    title: "Zuper Review (2026)",
    href: "/field-service/review/zuper",
    type: "Review",
    category: "Field Service",
    entity: "Zuper",
    keywords: ["zuper", "zuper review", "field service software"],
  },
  {
    title: "Square POS Review (2026)",
    href: "/pos/review/square-pos",
    type: "Review",
    category: "POS",
    entity: "Square POS",
    keywords: ["square", "square pos", "square review"],
  },
  {
    title: "Thumbtack Review (2026)",
    href: "/lead-generation/review/thumbtack",
    type: "Review",
    category: "Lead Generation",
    entity: "Thumbtack",
    keywords: ["thumbtack", "thumbtack review", "thumbtack leads"],
  },
  {
    title: "Google Local Services Ads Review (2026)",
    href: "/lead-generation/review/google-local-services-ads",
    type: "Review",
    category: "Lead Generation",
    entity: "Google Local Services Ads",
    keywords: ["google lsa", "local services ads", "google screened leads"],
  },
  {
    title: "Semrush Review (2026)",
    href: "/seo-tools/review/semrush",
    type: "Review",
    category: "SEO Tools",
    entity: "Semrush",
    keywords: ["semrush", "semrush review", "seo software"],
  },
  {
    title: "Ahrefs Review (2026)",
    href: "/seo-tools/review/ahrefs",
    type: "Review",
    category: "SEO Tools",
    entity: "Ahrefs",
    keywords: ["ahrefs", "ahrefs review", "backlink tool"],
  },
  {
    title: "BrightLocal Review (2026)",
    href: "/seo-tools/review/brightlocal",
    type: "Review",
    category: "SEO Tools",
    entity: "BrightLocal",
    keywords: ["brightlocal", "brightlocal review", "local seo software"],
  },
  {
    title: "CallRail Review (2026)",
    href: "/call-tracking/review/callrail",
    type: "Review",
    category: "Call Tracking",
    entity: "CallRail",
    keywords: ["callrail", "callrail review", "call tracking"],
  },
  {
    title: "CallTrackingMetrics Review (2026)",
    href: "/call-tracking/review/calltrackingmetrics",
    type: "Review",
    category: "Call Tracking",
    entity: "CallTrackingMetrics",
    keywords: ["calltrackingmetrics", "ctm", "call tracking analytics"],
  },
  {
    title: "WhatConverts Review (2026)",
    href: "/call-tracking/review/whatconverts",
    type: "Review",
    category: "Call Tracking",
    entity: "WhatConverts",
    keywords: ["whatconverts", "whatconverts review", "lead tracking"],
  },

  // ——— Alternatives ———
  {
    title: "Best Gusto Alternatives (2026)",
    href: "/payroll/alternatives/gusto",
    type: "Alternatives",
    category: "Payroll",
    entity: "Gusto",
    keywords: ["gusto", "gusto alternatives", "payroll alternatives"],
  },
  {
    title: "Best QuickBooks Online Alternatives (2026)",
    href: "/accounting/alternatives/quickbooks-online",
    type: "Alternatives",
    category: "Accounting",
    entity: "QuickBooks Online",
    keywords: ["quickbooks", "quickbooks alternatives", "accounting alternatives"],
  },
  {
    title: "Best HubSpot Alternatives (2026)",
    href: "/crm/alternatives/hubspot",
    type: "Alternatives",
    category: "CRM",
    entity: "HubSpot",
    keywords: ["hubspot", "hubspot alternatives", "crm alternatives"],
  },
  {
    title: "Best Zendesk Alternatives (2026)",
    href: "/helpdesk/alternatives/zendesk",
    type: "Alternatives",
    category: "Helpdesk",
    entity: "Zendesk",
    keywords: ["zendesk", "zendesk alternatives", "helpdesk alternatives"],
  },
  {
    title: "Best ServiceTitan Alternatives (2026)",
    href: "/field-service/alternatives/servicetitan",
    type: "Alternatives",
    category: "Field Service",
    entity: "ServiceTitan",
    keywords: ["servicetitan", "servicetitan alternatives", "field service alternatives"],
  },
  {
    title: "Best Connecteam Alternatives (2026)",
    href: "/field-service/alternatives/connecteam",
    type: "Alternatives",
    category: "Field Service",
    entity: "Connecteam",
    keywords: ["connecteam", "connecteam alternatives", "field service alternatives"],
  },
  {
    title: "Best Oracle Field Service Alternatives (2026)",
    href: "/field-service/alternatives/oracle-field-service",
    type: "Alternatives",
    category: "Field Service",
    entity: "Oracle Field Service",
    keywords: ["oracle field service", "oracle field service alternatives", "field service alternatives"],
  },
  {
    title: "Best Simpro Alternatives (2026)",
    href: "/field-service/alternatives/simpro",
    type: "Alternatives",
    category: "Field Service",
    entity: "Simpro",
    keywords: ["simpro", "simpro alternatives", "field service alternatives"],
  },
  {
    title: "Best Zuper Alternatives (2026)",
    href: "/field-service/alternatives/zuper",
    type: "Alternatives",
    category: "Field Service",
    entity: "Zuper",
    keywords: ["zuper", "zuper alternatives", "field service alternatives"],
  },
  {
    title: "Best Square POS Alternatives (2026)",
    href: "/pos/alternatives/square-pos",
    type: "Alternatives",
    category: "POS",
    entity: "Square POS",
    keywords: ["square", "square alternatives", "pos alternatives"],
  },
  {
    title: "Best Thumbtack Alternatives (2026)",
    href: "/lead-generation/alternatives/thumbtack",
    type: "Alternatives",
    category: "Lead Generation",
    entity: "Thumbtack",
    keywords: ["thumbtack", "thumbtack alternatives", "lead gen alternatives"],
  },
  {
    title: "Best Angi Alternatives (2026)",
    href: "/lead-generation/alternatives/angi",
    type: "Alternatives",
    category: "Lead Generation",
    entity: "Angi",
    keywords: ["angi", "angi alternatives", "homeadvisor angi leads"],
  },
  {
    title: "Best HomeAdvisor Alternatives (2026)",
    href: "/lead-generation/alternatives/homeadvisor",
    type: "Alternatives",
    category: "Lead Generation",
    entity: "HomeAdvisor",
    keywords: ["homeadvisor", "homeadvisor alternatives", "home services leads"],
  },
  {
    title: "Best Semrush Alternatives (2026)",
    href: "/seo-tools/alternatives/semrush",
    type: "Alternatives",
    category: "SEO Tools",
    entity: "Semrush",
    keywords: ["semrush alternatives", "seo software alternatives"],
  },
  {
    title: "Best Ahrefs Alternatives (2026)",
    href: "/seo-tools/alternatives/ahrefs",
    type: "Alternatives",
    category: "SEO Tools",
    entity: "Ahrefs",
    keywords: ["ahrefs alternatives", "seo tools like ahrefs"],
  },
  {
    title: "Best Moz Pro Alternatives (2026)",
    href: "/seo-tools/alternatives/moz-pro",
    type: "Alternatives",
    category: "SEO Tools",
    entity: "Moz Pro",
    keywords: ["moz pro alternatives", "moz alternatives"],
  },
  {
    title: "Best CallRail Alternatives (2026)",
    href: "/call-tracking/alternatives/callrail",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "CallRail",
    keywords: ["callrail alternatives", "call tracking alternatives"],
  },
  {
    title: "Best CallTrackingMetrics Alternatives (2026)",
    href: "/call-tracking/alternatives/calltrackingmetrics",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "CallTrackingMetrics",
    keywords: ["calltrackingmetrics alternatives", "ctm alternatives"],
  },
  {
    title: "Best WhatConverts Alternatives (2026)",
    href: "/call-tracking/alternatives/whatconverts",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "WhatConverts",
    keywords: ["whatconverts alternatives", "lead reporting alternatives"],
  },
  {
    title: "Best Ringba Alternatives (2026)",
    href: "/call-tracking/alternatives/ringba",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "Ringba",
    keywords: ["ringba alternatives", "pay per call software alternatives"],
  },
  {
    title: "Best Invoca Alternatives (2026)",
    href: "/call-tracking/alternatives/invoca",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "Invoca",
    keywords: ["invoca alternatives", "conversation intelligence alternatives"],
  },
  {
    title: "Best Twilio Alternatives (2026)",
    href: "/call-tracking/alternatives/twilio",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "Twilio",
    keywords: ["twilio alternatives", "programmable voice alternatives"],
  },
  {
    title: "Best PhoneWagon Alternatives (2026)",
    href: "/call-tracking/alternatives/phonewagon",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "PhoneWagon",
    keywords: ["phonewagon alternatives", "simple call tracking alternatives"],
  },
  {
    title: "Best Nimbata Alternatives (2026)",
    href: "/call-tracking/alternatives/nimbata",
    type: "Alternatives",
    category: "Call Tracking",
    entity: "Nimbata",
    keywords: ["nimbata alternatives", "gdpr call tracking alternatives"],
  },

  // ——— Comparisons ———
  {
    title: "Gusto vs OnPay (2026)",
    href: "/payroll/compare/gusto-vs-onpay",
    type: "Comparison",
    category: "Payroll",
    keywords: ["gusto", "onpay", "gusto vs onpay", "payroll comparison"],
  },
  {
    title: "Gusto vs QuickBooks Payroll (2026)",
    href: "/payroll/compare/gusto-vs-quickbooks-payroll",
    type: "Comparison",
    category: "Payroll",
    keywords: ["gusto", "quickbooks payroll", "gusto vs quickbooks"],
  },
  {
    title: "HubSpot vs Salesforce (2026)",
    href: "/crm/compare/hubspot-vs-salesforce",
    type: "Comparison",
    category: "CRM",
    keywords: ["hubspot", "salesforce", "hubspot vs salesforce", "crm comparison"],
  },
  {
    title: "Zendesk vs Freshdesk (2026)",
    href: "/helpdesk/compare/zendesk-vs-freshdesk",
    type: "Comparison",
    category: "Helpdesk",
    keywords: ["zendesk", "freshdesk", "zendesk vs freshdesk", "helpdesk comparison"],
  },
  {
    title: "ServiceTitan vs Jobber (2026)",
    href: "/field-service/compare/servicetitan-vs-jobber",
    type: "Comparison",
    category: "Field Service",
    keywords: ["servicetitan", "jobber", "servicetitan vs jobber", "field service comparison"],
  },
  {
    title: "Simpro vs ServiceTitan (2026)",
    href: "/field-service/compare/simpro-vs-servicetitan",
    type: "Comparison",
    category: "Field Service",
    keywords: ["simpro", "servicetitan", "simpro vs servicetitan", "field service comparison"],
  },
  {
    title: "Zuper vs Jobber (2026)",
    href: "/field-service/compare/zuper-vs-jobber",
    type: "Comparison",
    category: "Field Service",
    keywords: ["zuper", "jobber", "zuper vs jobber", "field service comparison"],
  },
  {
    title: "Connecteam vs Jobber (2026)",
    href: "/field-service/compare/connecteam-vs-jobber",
    type: "Comparison",
    category: "Field Service",
    keywords: ["connecteam", "jobber", "connecteam vs jobber", "field service comparison"],
  },
  {
    title: "Square POS vs Shopify POS (2026)",
    href: "/pos/compare/square-pos-vs-shopify-pos",
    type: "Comparison",
    category: "POS",
    keywords: ["square pos", "shopify pos", "square vs shopify", "pos comparison"],
  },
  {
    title: "Thumbtack vs Angi (2026)",
    href: "/lead-generation/compare/thumbtack-vs-angi",
    type: "Comparison",
    category: "Lead Generation",
    keywords: ["thumbtack", "angi", "thumbtack vs angi", "lead generation comparison"],
  },
  {
    title: "Google LSA vs Yelp Ads (2026)",
    href: "/lead-generation/compare/google-local-services-ads-vs-yelp-ads",
    type: "Comparison",
    category: "Lead Generation",
    keywords: ["google lsa", "yelp ads", "local services ads vs yelp", "local lead ads"],
  },
  {
    title: "Semrush vs Ahrefs (2026)",
    href: "/seo-tools/compare/semrush-vs-ahrefs",
    type: "Comparison",
    category: "SEO Tools",
    keywords: ["semrush vs ahrefs", "ahrefs vs semrush", "seo comparison"],
  },
  {
    title: "BrightLocal vs Whitespark (2026)",
    href: "/seo-tools/compare/brightlocal-vs-whitespark",
    type: "Comparison",
    category: "SEO Tools",
    keywords: ["brightlocal vs whitespark", "local seo comparison"],
  },
  {
    title: "CallRail vs CallTrackingMetrics (2026)",
    href: "/call-tracking/compare/callrail-vs-calltrackingmetrics",
    type: "Comparison",
    category: "Call Tracking",
    keywords: ["callrail vs calltrackingmetrics", "callrail vs ctm", "call tracking comparison"],
  },
  {
    title: "CallRail vs WhatConverts (2026)",
    href: "/call-tracking/compare/callrail-vs-whatconverts",
    type: "Comparison",
    category: "Call Tracking",
    keywords: ["callrail vs whatconverts", "whatconverts vs callrail"],
  },

  // ——— Best software roundups ———
  {
    title: "Best Payroll Software (2026)",
    href: "/payroll/best-payroll-software",
    type: "Best Software",
    category: "Payroll",
    keywords: ["payroll software", "best payroll", "best payroll software"],
  },
  {
    title: "Best Accounting Software (2026)",
    href: "/accounting/best-accounting-software",
    type: "Best Software",
    category: "Accounting",
    keywords: ["accounting software", "best accounting", "best accounting software"],
  },
  {
    title: "Best CRM Software (2026)",
    href: "/crm/best-crm-software",
    type: "Best Software",
    category: "CRM",
    keywords: ["crm software", "best crm", "best crm software"],
  },
  {
    title: "Best Helpdesk Software (2026)",
    href: "/helpdesk/best-helpdesk-software",
    type: "Best Software",
    category: "Helpdesk",
    keywords: ["helpdesk software", "best helpdesk", "best helpdesk software"],
  },
  {
    title: "Best Field Service Software (2026)",
    href: "/field-service/best-field-service-software",
    type: "Best Software",
    category: "Field Service",
    keywords: ["field service software", "best field service"],
  },
  {
    title: "Best POS Software (2026)",
    href: "/pos/best-pos-software",
    type: "Best Software",
    category: "POS",
    keywords: ["pos software", "best pos", "best pos software"],
  },
  {
    title: "Best Inventory Software (2026)",
    href: "/inventory/best-inventory-software",
    type: "Best Software",
    category: "Inventory",
    keywords: ["inventory software", "best inventory", "best inventory software"],
  },
  {
    title: "Best HR Software (2026)",
    href: "/hr/best-hr-software",
    type: "Best Software",
    category: "HR",
    keywords: ["hr software", "best hr", "best hr software"],
  },
  {
    title: "Best Scheduling Software (2026)",
    href: "/scheduling/best-scheduling-software",
    type: "Best Software",
    category: "Scheduling",
    keywords: ["scheduling software", "best scheduling", "best scheduling software"],
  },
  {
    title: "Best Time Tracking Software (2026)",
    href: "/time-tracking/best-time-tracking-software",
    type: "Best Software",
    category: "Time Tracking",
    keywords: ["time tracking software", "best time tracking"],
  },
  {
    title: "Best Website Builders (2026)",
    href: "/website-builders/best-website-builders",
    type: "Best Software",
    category: "Website Builders",
    keywords: ["best website builders", "contractor website builder", "small business website builder"],
  },
  {
    title: "Best Lead Generation Tools (2026)",
    href: "/lead-generation/best-lead-generation-tools",
    type: "Best Software",
    category: "Lead Generation",
    keywords: ["best lead generation tools", "contractor leads", "local service leads"],
  },
  {
    title: "Best SEO Tools (2026)",
    href: "/seo-tools/best-seo-tools",
    type: "Best Software",
    category: "SEO Tools",
    keywords: ["best seo tools", "local seo software", "contractor seo tools"],
  },
  {
    title: "Best Call Tracking Software (2026)",
    href: "/call-tracking/best-call-tracking-software",
    type: "Best Software",
    category: "Call Tracking",
    keywords: ["best call tracking software", "callrail", "marketing call attribution"],
  },

  // ——— Best-for pages (selected high-intent) ———
  {
    title: "Best Payroll Software for Small Business",
    href: "/payroll/best-for/small-business",
    type: "Best For",
    category: "Payroll",
    keywords: ["payroll", "small business", "best payroll for small business"],
  },
  {
    title: "Best Payroll Software for Contractors",
    href: "/payroll/best-for/contractors",
    type: "Best For",
    category: "Payroll",
    keywords: ["payroll", "contractors", "best payroll for contractors"],
  },
  {
    title: "Best Field Service Software for HVAC",
    href: "/field-service/best-for/hvac",
    type: "Best For",
    category: "Field Service",
    keywords: ["field service", "hvac", "hvac software"],
  },
  {
    title: "Best Field Service Software for Plumbing",
    href: "/field-service/best-for/plumbing",
    type: "Best For",
    category: "Field Service",
    keywords: ["field service", "plumbing", "plumbing software"],
  },
  {
    title: "Best POS for Small Business",
    href: "/pos/best-for/small-business",
    type: "Best For",
    category: "POS",
    keywords: ["pos", "small business", "best pos for small business"],
  },
  {
    title: "Best Inventory Software for Small Business",
    href: "/inventory/best-for/small-business",
    type: "Best For",
    category: "Inventory",
    keywords: ["inventory", "small business", "inventory software for small business"],
  },
  {
    title: "Best Website Builders for Contractors",
    href: "/website-builders/best-for/contractors",
    type: "Best For",
    category: "Website Builders",
    keywords: ["website builder", "contractors", "best website builder for contractors"],
  },

  // ——— Guides (major) ———
  {
    title: "How Payroll Software Works",
    href: "/payroll/guides/how-payroll-software-works",
    type: "Guide",
    category: "Payroll",
    keywords: ["how payroll software works", "payroll guide"],
  },
  {
    title: "How to Choose Field Service Software",
    href: "/field-service/guides/how-to-choose-field-service-software",
    type: "Guide",
    category: "Field Service",
    keywords: ["how to choose field service software", "field service guide"],
  },
  {
    title: "Best HR Software for Small Business",
    href: "/hr/guides/best-hr-software-for-small-business",
    type: "Guide",
    category: "HR",
    keywords: ["hr software", "best hr software for small business"],
  },
  {
    title: "Project Management for Small Business",
    href: "/project-management/guides/project-management-for-small-business",
    type: "Guide",
    category: "Project Management",
    keywords: ["project management", "small business", "project management guide"],
  },
  {
    title: "Helpdesk Software for Startups",
    href: "/helpdesk/guides/helpdesk-software-for-startups",
    type: "Guide",
    category: "Helpdesk",
    keywords: ["helpdesk", "startups", "helpdesk software for startups"],
  },
  {
    title: "Inventory Software for Ecommerce",
    href: "/inventory/guides/inventory-software-for-ecommerce",
    type: "Guide",
    category: "Inventory",
    keywords: ["inventory", "ecommerce", "inventory software for ecommerce"],
  },
  {
    title: "How to Choose a Website Builder",
    href: "/website-builders/guides/how-to-choose-a-website-builder",
    type: "Guide",
    category: "Website Builders",
    keywords: ["how to choose a website builder", "website builder guide", "service business website"],
  },
  {
    title: "How to Get Leads for Contractors",
    href: "/lead-generation/guides/how-to-get-leads-for-contractors",
    type: "Guide",
    category: "Lead Generation",
    keywords: ["contractor leads", "how to get leads", "trade lead generation"],
  },
  {
    title: "How to Choose a Lead Generation Platform",
    href: "/lead-generation/guides/how-to-choose-a-lead-generation-platform",
    type: "Guide",
    category: "Lead Generation",
    keywords: ["lead generation platform", "choose lead gen software", "local leads guide"],
  },
  {
    title: "Hostinger vs Wix",
    href: "/website-builders/compare/hostinger-website-builder-vs-wix",
    type: "Comparison",
    category: "Website Builders",
    keywords: ["hostinger website builder", "wix", "hostinger vs wix"],
  },
  {
    title: "GoDaddy vs Hostinger",
    href: "/website-builders/compare/godaddy-website-builder-vs-hostinger-website-builder",
    type: "Comparison",
    category: "Website Builders",
    keywords: ["godaddy website builder", "hostinger", "godaddy vs hostinger"],
  },
  {
    title: "Best SEO Tools for Contractors",
    href: "/seo-tools/best-for/contractors",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["seo tools contractors", "contractor seo", "local seo contractors"],
  },
  {
    title: "Best SEO Tools for Local SEO",
    href: "/seo-tools/best-for/local-seo",
    type: "Best For",
    category: "SEO Tools",
    keywords: ["best local seo tools", "map pack seo software"],
  },
  {
    title: "How to Do SEO for Contractors",
    href: "/seo-tools/guides/how-to-do-seo-for-contractors",
    type: "Guide",
    category: "SEO Tools",
    keywords: ["contractor seo guide", "local seo contractors", "trade seo"],
  },
  {
    title: "How to Rank in Google Maps",
    href: "/seo-tools/guides/how-to-rank-in-google-maps",
    type: "Guide",
    category: "SEO Tools",
    keywords: ["google maps ranking", "map pack seo", "local pack"],
  },
  {
    title: "Best Call Tracking for Contractors",
    href: "/call-tracking/best-for/contractors",
    type: "Best For",
    category: "Call Tracking",
    keywords: ["call tracking contractors", "contractor call attribution", "lsa call tracking"],
  },
  {
    title: "What Is Call Tracking?",
    href: "/call-tracking/guides/what-is-call-tracking",
    type: "Guide",
    category: "Call Tracking",
    keywords: ["what is call tracking", "dynamic number insertion", "dni"],
  },
  {
    title: "How Call Tracking Works",
    href: "/call-tracking/guides/how-call-tracking-works",
    type: "Guide",
    category: "Call Tracking",
    keywords: ["how call tracking works", "call tracking setup"],
  },
];

